guiclient/postCheck.cpp
guiclient/postChecks.cpp
guiclient/printCheck.cpp

Looks like the initial population of the Bank Account was not triggering the signal to update the payments combo.  Added an explicit call to sHandleBankAccount function to resolve this issue.
Plus there was a logic bug introduced with the 4.8 non-check printing Bank Account logic also resolved here.

Issue #25163 Cannot post/Print checks

---

guiclient/main.cpp

Also tweaks license expiry message to refer to obtaining a new license rather than payment (Issue #25350).

Issue #25311: Better client mismatch message

---

widgets/currCluster.cpp

Tweak minimum size so that the curr dropdown does not overlap the money edit.
Need regression testing on Windows and Mac OS (I don't have the build environment for that)  but cannot envisage an issue.

Issue #25003: CurrCluster size issue on Linux OS.

---

guiclient/viewCheckRun.ui

This makes the button more generic, as it is not always used to print if EFT is used or if some checks are written by hand.

Make Print button more generic on check run tab

---

guiclient/printCheck.cpp
guiclient/printCheck.h
guiclient/printCheck.ui

If a check has been written by hand, or if an electronic payment sent from an account, this allows the user to fill in the check number or electronic transaction number as the document number without actually printing any check.

Record individual payments without printing

---

common/login2.cpp
common/login2.h
guiclient/company.cpp
guiclient/databaseInformation.cpp
guiclient/main.cpp
guiclient/syncCompanies.cpp
guiclient/version.cpp
guiclient/version.h

This pull request is to present the work that has been started and to begin discussion for the changes necessary to completely resolve [Issue #25072](http://www.xtuple.org/xtincident/view/bugs/25072).
Requires PR xtuple/xtuple#2242.
This patch implements database connection naming using the "application_name" connection parameter to help identify the client connections. Once that was in place I was able to simplify the connection counting routine to focus only on activity reported in "pg_stat_activity". The previous process was going through the extra effort to explicitly count the advisory locks acquired by the application, at this point I'm not sure which one is preferred so I am starting with the simplest.
I have verified that the license enforcement works properly based on the …

Issue #25072: Purchased xTuple licenses are consumed by non xTuple DB connections.

---

guiclient/purchaseOrder.cpp

Not entirely sure if this completely resolves the constraint based error message as it only appeared once for me then I did not get the error again despite logging out and in again.
This should catch the problem before the error initiates.

Issue #25165: Add user-friendly error message for missing PO number

---

widgets/crmacctCluster.cpp

Previous fix addressed the Vendor List screen.  This resolves the issue in the Vendor Search (crmacct) Widget and List.

Issue #24953: Display correct Vendor Address in Vendor Search widget

---

scriptapi/qapplicationproto.cpp
scriptapi/qapplicationproto.h
scriptapi/scriptapi.pro
scriptapi/setupscriptapi.cpp

This change is intended to aid in the current UI/UX push. It should now be possible to script something like
```JavaScript
QApplication.styleSheet = "QPushButton { background-color: red; }";
QApplication.styleSheet += "QComboBox { border-left-style: dotted; border-right-style: dotted; }";
```
and other such silliness.

first pass at exposing QApplication singleton

---

guiclient/displays/dspTimePhasedOpenAPItems.cpp
guiclient/displays/dspTimePhasedOpenAPItems.h
guiclient/displays/dspTimePhasedOpenAPItems.ui
guiclient/displays/dspTimePhasedOpenARItems.cpp
guiclient/displays/dspTimePhasedOpenARItems.h
guiclient/displays/dspTimePhasedOpenARItems.ui

New AP and AR Aging summary reports. User selectable
Requires xtuple/xtuple#2256

Issue #6664: Allow user selection of AR/AP Aging summary vs detailed rpt

---

guiclient/group.cpp
guiclient/user.cpp

Privilege descriptions get loaded and saved but are not displayed anywhere.  Add to Roles and User screens to give users more information about the permissions they are assigning.

Issue #25509: Add privilege descriptions to screens 

---

guiclient/createLotSerial.cpp
guiclient/createLotSerial.h
guiclient/displays/dspDetailedInventoryHistoryByLotSerial.cpp
guiclient/issueLineToShipping.cpp
guiclient/issueToShipping.cpp
guiclient/lotSerialUtils.cpp

Modify Inventory History report to display Lot/Serial Expiration on screen and report.
Also resolves issue where expiration and warranty dates were lost from the system when item quantity fully shipped on Transfer Orders.
Fixes incorrect display of Lot characteristics after Lot creation
Handles duplicated lsdetail entries when TO is issued to shipment then returned
Requires schema change on xtuple/private-extensions#582
Covers Issues #24240, #25600, #24443

Issue #25600: Resolve various Lot/Serial and Transfer order issues

---

guiclient/salesOrder.cpp

Add separate privilege to SO hold type to allow user to create a SO but not necessarily override customer credit hold
Requires xtuple/xtuple#2260

Issue #12336: Add SO Hold Type override privilege

---

guiclient/saleType.cpp
guiclient/saleType.h
guiclient/saleType.ui
guiclient/saleTypes.cpp
widgets/xcombobox.cpp

SO defaulted to first alphabetically listed Sale Type when not manually set. The default could change if Sale Types were updated.  This change allows a default Sale Type to be set and used in SO automatically.
Requires by xtuple/xtuple#2262

Issue #25612: Add Sale Type default checkbox to set up to fix SO bug

---

common/metrics.cpp
guiclient/main.cpp

This PR reduces the number of database queries run during login. I made the changes trying to track down a database error that occurred when loading the metrics, hence https://github.com/xtuple/qt-client/commit/4c342032a6a29320d4e3a9781a99ed58494b2425 Restarting Postgres fixed the problem (something about SSL header length) but the code changes still seem worthwhile.

reorder login metrics fetch

---

guiclient/salesOrderItem.cpp
guiclient/salesOrderItem.ui

Add checkbox to SO Item screen.  If checked refresh SO Header on save (status quo).  If unchecked, refresh once when exiting the SO Item screen.
Requested to assist SO performance on large orders.

Issue #25187: Allow user to turn off immediate Order Header refresh

---

common/applock.cpp
common/applock.h
guiclient/purchaseOrder.cpp
guiclient/salesOrder.cpp
guiclient/transferOrder.cpp

issue #25676 - extend the API for AppLock so it can either report its own errors or let the caller do it, then change existing callers to use the revised version

issue #25676 - make applock optionally interactive

---

guiclient/vendor.cpp

Creating Vendor from the New set a different Misc. Account determination, than creating a vendor from   CRM account

Issue #20770: Ensure consistency when creating Vendors via different paths

---

guiclient/printArOpenItem.cpp

the .toChar().toAscii() was returning some weird character not able to be interpreted in the switch so always reverted to the default case.

Issue #21922: Fix missing applications on AR Open Item report

---

guiclient/distributeInventory.cpp
guiclient/distributeInventory.h
guiclient/distributeInventory.ui
guiclient/locations.cpp
guiclient/locations.h
guiclient/locations.ui

Used where significant warehouses are broken into several zones

Issue #25702 Add Zone filtering in Location and Inventory Distribution screens

---

guiclient/item.cpp

Some elements were not disabled when locked items switched to view mode.  Resolved that per standard view mode of items.

Issue #24940: Fix residual view mode enabled items for locked items

---

guiclient/bomItem.cpp

Add check to BOM item addition to prevent if the item is job costed.  Apparently causes all sorts of costing issues and orphaned elements.

Issue #24663: Prevent addition of jobcosted items to BOMs

---

guiclient/salesOrder.cpp

When Ship To widget is cleared SO is now reset back to customer defaults

Issue #25727: Sales Order was not resetting when Ship To cleared

---

guiclient/bankAccount.ui
guiclient/cashReceipt.ui
guiclient/check.ui
guiclient/configureGL.ui
guiclient/configureSO.ui
guiclient/dspCheckRegister.cpp
guiclient/dspCheckRegister.ui
guiclient/returnAuthCheck.ui
guiclient/returnAuthorization.ui
guiclient/returnAuthorizationWorkbench.ui
guiclient/salesOrder.ui
guiclient/vendor.ui

Modifies various screens to replace reference to "Checks" with "Payment" to ensure consistency across the application.

Issue #25701: Alter various screens to replace reference to Check to Paymnt.

---

guiclient/itemUOM.cpp

Stop user from cancelling if they have removed conversion type.
There are quite a few holes in the uom area coming out of investigating this issue.

Issue #25728: prevent missing uom conversion type when cancelling screen

---

guiclient/createLotSerial.cpp

When returning Lot Qty greater than issued Qty an error occurred (when the lot was issued multiple times).  This fix sums the qty issued to check the correct value.

Issue #25665: Fix WO Material Return for Lot Items with different qtys

---

guiclient/creditMemoItem.cpp
guiclient/invoiceItem.cpp
guiclient/item.cpp
guiclient/itemPricingScheduleItem.cpp
guiclient/itemUOM.cpp
guiclient/itemUOM.ui
guiclient/returnAuthorizationItem.cpp
guiclient/salesOrderItem.cpp
guiclient/woMaterialItem.cpp

Build in ability to deactivate Item UoM conversions
Screens previously running individual, duplicated SQL now reference single metaSQL and take account of active status of conversion.
Screens also consistently take account of the conversion "type" (e.g Selling) which they were not previously with potentially confusing results.
requires xtuple/xtuple#2299

Issue #25729: Various UOM handling improvements and consistency

---

guiclient/company.cpp
guiclient/configureGL.cpp

Convert default from expense to liability in the configure Accounting and Company screens

Issue #25838: Convert unassigned account widget to Liability default

---

guiclient/reconcileBankaccount.cpp

Remove reference to uomratio and set exchange rate to 6 decimal places to ensure sufficient decimal places in the Bank Reconciliation screen and to ensure consistency between the metaSQL and the application.
Requires xtuple/xtuple#2313 and xtuple/xtuple#2316

Issue #25836: Insufficient decimal places in Bank Rec screen

---

guiclient/customer.cpp

Fix invalid lock when opening Customer Workbench.  Also found missing lock check in unit testing so resolved that as well.  Checked Vendor Workbench for same problem, but this screen works completely differently.

Issue #25719: Invalid lock error in Customer Workbench

---

guiclient/vendor.ui

Missed in previous PR.
Question though - why do we have a Payments radio on the Vendor ui and then immediately upon selection have a checkbox enabling EFT payments?  Could just be the one option?

Issue #25701: Modify reference to check on Vendor screen

---

guiclient/project.cpp

Could not correctly assign an order (SO/PO/WO) to a new Project as it had not yet been saved (and there are rollback issues).  So only allow order assignment on edited projects
Also resolve refresh of task/order list upon order assignment.

Issue #25985: Resolve new project handling and list refreshing

---

guiclient/salesOrderItem.ui

Remove new widget focus so the initial focus returns to the item widget.

Issue #25952: Resolve SalesOrderItem ui focus

---

guiclient/creditcardprocessor.cpp

See https://github.com/xtuple/qt-client/blob/4_9_x/guiclient/creditcardprocessor.cpp#L1858-L1865 for the significance of `-18`.

issue #23885 - address payco err when using yourpay

---

widgets/characteristicAssignment.cpp

Possibly need to revisit this as the setting to allow/disallow the default flag on characteristics is currently hard-coded against Characteristic Types

Issue #25931: Allow Item Group characteristic defaults

---

common/login2.cpp

Also fixes the same issue in the 'port' field on the login screen.

Issue #25697:Login Screen Database Name Cursor Jumps

---

guiclient/scriptEditor.cpp

Export function of xtreewidget uses QTextDocument which doesn't have a way to specify to use te byte oder mark, would need refactoring to use QTextStream if it is required there (that data exports in UTF8 fine, but has no byte order mark. Might not be an issue if that data isn't reimported)

Fixes issue #15457 - textstreams saved as UTF-8 on windows were not written with BOM

---

guiclient/configureSO.cpp
guiclient/configureSO.ui
guiclient/openReturnAuthorizations.cpp
guiclient/openReturnAuthorizations.h
guiclient/openReturnAuthorizations.ui

Based on config setting (metric) automatically close the Return Auth when a credit memo is created.  Prevents partially credited RA's from remaining open indefinitely.  Also adds the capability for a user to manually close an RA via the Open Return Auths screen (as opposed to completely deleting RAs)
Requires xtuple/private-extensions#657
@gilmoskowitz in looking at this issue it seems we post RA information to a rahist table but I cannot find any screen/report/form that references this table so it looks like we lose all visibility of an RA once it is closed/credited.  We probably should add some display/report to show RA history.

Issue #25927: Close Return Authorisation upon Crediting

---

guiclient/apOpenItem.cpp
guiclient/apOpenItem.h
guiclient/apOpenItem.ui

Remove Accounting Tab and move Distribution account to main window to improve visibility.  Reverse behaviour so selecting the checkbox picks the Prepaid account, unchecking expects an Account to be selected.

Issue #18174 Reverse Behavior on Miscellaneous AP Credit Memo

---

guiclient/creditMemo.cpp
guiclient/creditMemo.ui
guiclient/creditMemoItem.cpp
guiclient/creditMemoItem.h
guiclient/creditMemoItem.ui
guiclient/customerFormAssignment.ui
guiclient/customerFormAssignments.cpp
guiclient/dspAROpenItems.cpp
guiclient/invoice.cpp
guiclient/menuSales.cpp
guiclient/printCreditMemo.ui
guiclient/printCreditMemos.ui
guiclient/reprintCreditMemos.ui
guiclient/unpostedCreditMemos.cpp
guiclient/unpostedCreditMemos.ui

Add Misc. (non-inventory) items to Credit Memos thus making them proper Credit Memos (reverse Invoices).  Also complete work on alternate revenue account per item (same as Invoice item logic).
Revert naming back from Return to Credit Memo as the functionality is now much more than just returning items.  Also converted Invoice and Credit Memo item list to metaSQL
requires xtuple/xtuple#2480

Issue #26424: Add Misc Items to Credit Memos, Alt Revenue Accnt

---

guiclient/guiclient.cpp
guiclient/guiclient.h
guiclient/systemMessage.cpp
guiclient/systemMessage.h

for msgs that are already open.
This is an experiment. If it works then we should consider propagating the idea throughout the application. I think this is what https://github.com/xtuple/qt-client/blob/4_10_x/guiclient/salesOrder.cpp#L3647-L3740 is trying to accomplish, for example.

issue #26546 - show existing windows instead of creating new ones

---

widgets/vendorgroup.h

Tested Vendor screen, AP Workbench could find no issues with removing this slot.
Tested scripting and this *has* fixed my original scripting problem

Remove ambiguous VendorGroup slot

---

common/xbase32.cpp

char is unsigned by default on ARM cpu's and single board computers. Explicitly declaring these instances to be signed fixes the registration key code on ARM builds. 
Tested on x86_64 as well to make sure I didn't break something else (but really all this is doing is what the x86 CXXFLAGS dictate normally anyways)

Fixing char declarations so registration key code works on ARM devices

---

guiclient/salesOrder.cpp

Only refresh if no packdate exists to avoid overwriting

Issue #26804: Sales Order Pack Date

---

common/errorReporter.cpp
guiclient/projectType.cpp
guiclient/projectTypes.cpp

Fix involves three files: errorReporter.cpp, projectType.cpp and projectTypes.cpp.
In the first, added a human readable error for prj_prj_prjtype_id_fkey.  In the others, added call to ErrorReporter on delete where there was no call.

issue #26653 

---

guiclient/display.ui

Query fields now remain anchored at the left if you grab the screen and resize it.  If the screen gets TOO big then the query fields float just a tad to the right...but not all the way into the middle like they were doing previously.

issue #26956 Query fields not remaining anchored - resolved

---

guiclient/returnAuthorizationWorkbench.cpp

Obtained cohead_id.  If same is > 0, then passing 'cohead' as the reference type so that postCCCredit will use the prepaid account instead of A/R.  Also removed tabs on affected lines.
This pull request depends on a corresponding pull request in the tuple repository (a single modification to a MetaSQL).

issue #26638: Passed additional reference data to credit so that postCCCredit would use prepaid account rather than A/R

---

guiclient/menuProducts.cpp
guiclient/menuSystem.cpp

Reverted to same approach as the other menus.  Cannot test on Mac, but have tested on my build and changes are working.

Issue #26796: Fix Setup menu text (on Mac)

---

guiclient/xmainwindow.cpp
guiclient/xwidget.cpp

tested on Windows and OS X, workspace and free-floating modes

issue #27142 - fix window memory in MDI context

---

guiclient/databaseInformation.cpp
guiclient/databaseInformation.ui
guiclient/main.cpp
guiclient/user.cpp
guiclient/userPreferences.cpp
guiclient/userPreferences.h

Configurable setup switch to enforce password age and the number of days.
Save reset date when user edits passwords (user and user pref screens)
Check for switch and age of user password when logging in - if required, prompt/warn user and then open userPreferences screen on the password tab.

Issue #27056: PCI Compliance: configurable password update enforcement

---

guiclient/inputManager.cpp
guiclient/inputManager.h
guiclient/inputManagerPrivate.h

The old bar code scanning code emitted distinct signals for different scans. That's really hard to extend. The simplification of the scanning code for 4.10.0-beta overlooked the need for this, though:-(

Issue #27298 - emit a general-purpose signal when a bar code has been scanned

---

guiclient/project.ui

Project List header and Tab had different names.
Customer feedback

Issue #27367: Rename Project Notes tab to ensure consistency with list

---

guiclient/images.cpp
guiclient/images.ui

Convert Images List from embedded SQL to metaSQL.  Allows choosing to calculate image size or not.  Significant performance gain on Db with a lot of images if the size is not calculated.
Requires xtuple/xtuple#2589

issue #27365: Item images metasql

---

guiclient/dspBankrecHistory.ui

Was unreadable under some circumstances at customer site.

Set minimum width of Bank Rec History combobox

---

scriptapi/qapplicationproto.cpp
scriptapi/qapplicationproto.h
scriptapi/qcoreapplicationproto.cpp
scriptapi/qcoreapplicationproto.h
scriptapi/scriptapi.pro
scriptapi/setupscriptapi.cpp

This allows the script that launches the Trojita clients to search starting at the _application_'s directory instead of some arbitrary place (perhaps the user's home directory or current working directory). The fix for the bug itself is in the [connect](https://github.com/xtuple/connect) repository.

issue #26428 - expose qcoreapplication to scripting

---

guiclient/menuAccounting.cpp
guiclient/menuCRM.cpp
guiclient/menuInventory.cpp
guiclient/menuManufacture.cpp
guiclient/menuProducts.cpp
guiclient/menuPurchase.cpp
guiclient/menuSales.cpp
guiclient/menuSchedule.cpp
guiclient/menuSystem.cpp

Create menu actions even when the menu items are invisible. This allows fixing the xtSetup bug, done by a separate pull request in the [custom](https://github.com/xtuple/custom) repository.

issue #25967 - create actions whether menu item is visible or not

---

guiclient/xdialog.cpp

Receipts of serial items got really messed up. The distribution windows were not updating themselves properly in response to child dialog success. Therefore, the serial numbers were not being selected, distributed, or otherwise properly recognized.

issue #26705, issue #22850 - fix distribution of t/o receipt serial items

---

guiclient/reconcileBankaccount.cpp
widgets/xtreewidget.cpp
widgets/xtreewidget.h

Determined that "old style" sorting was being used because no column names were assigned when adding the columns to the _receipts XTreeWidget.  Adding column names fixed that part.  Also determined that the XTreeWidgetItem constructor that had been used always created QString variants for the raw data (which is what is sorted).  While sort code existed to handle numerics as strings, such logic was not present for dates as strings.
My solution was to set each column data individually with either setText or the new functions setDate and setNumber on XTreeWidgetItem.  These latter set the raw data to the correct type variants and apply the appropriate Qt::DisplayRole formatting.

issue #21265 - Column sorting on Bank Reconciliation screen

---

guiclient/authorizedotnetprocessor.cpp

Initialize isCP variable to false. Otherwise response from authorize.net is treated improperly as a card-present.

Issue 27643

---

debian/changelog
guiclient/Info.plist
guiclient/displays/dspBookings.cpp
guiclient/version.cpp

Unit tested the one code change and confirmed that the 4.9.4 application will connect to a 4.9.3 database without error or warning.
@dpocock - Could you please review and let me know if anything else is required at this time?

fix bad method call to allow compiling for upcoming fedora release

---

guiclient/currencyConversion.cpp

Extend entry of Exchange Rate to 6 decimal places which is required to avoid 0.01 rounding issues in the Bank Reconciliation.
The scenario mentioned in the issue appeared resolved as a result of this change (no rounding issues in the Bank Rec.) but I cannot guarantee this is the entire solution.

Issue #24549: Resolve some currency conversion issues

---

guiclient/characteristic.cpp
guiclient/characteristic.ui
guiclient/lotSerial.cpp
guiclient/lotSerialUtils.cpp

This PR resolves the core issue and improves the URL validator regexp.
However I found the reason the [Y/N] validator was missing looked to be the XComboBox AllowNull string was overriding the first item in the dropdown item list.
This may indicate a wider problem with fixed XComboBox lists elsewhere in the system.   Qt5 or Unicode problem ??
Also resolves Issue #25878 Characteristic Input Mask and Validator not working for Lot/Serial input
AND Issue #27323: New button on Lot/Serial characteristics

issue #27633, issue #25878 - characteristic Validators, issue #26893 - lot/serial screen fixes

---

guiclient/enterPoReceipt.cpp

Fix issue 25587 with partially drop-shipped SalesOrder. Requires changes to shiphead table to track if it's a dropship. See xtuple/xtuple#2664 in foundation db.

Issue #25587 - partial drop-shipped orders

---

guiclient/financialLayout.ui

Straightforward default index fix. Tested and confirmed working.

issue #27749 Fixed default tab for Financial Report screen

---

guiclient/distributeInventory.cpp
guiclient/distributeToLocation.cpp
guiclient/distributeToLocation.h

Changed prompt to warning when issuing more items than available. Action is disallowed instead of simply discouraged.

issue #27691 Issuing multiple quantity of same serial number

---

guiclient/enterPoitemReceipt.cpp
guiclient/enterPoitemReceipt.ui

Clarify Goods Receipt screens for non-inventory items so users know what they actually should be receipting/confirming.
requires xtuple/xtuple#2672

Issue #27807: Clarify Non-Inventory PO items on PO form and Goods Receipt

---

widgets/comments.cpp

Changed the comments widget so that the new comment button is disabled until an item has been selected to post a comment to.

issue #27832 Prevent adding a comment without a source

---

guiclient/cashReceipt.cpp
guiclient/cashReceiptMiscDistrib.cpp

* Eliminated unnecessary label when adding a miscellaneous distribution using Customer and not Customer Group.
* Fixed changing Customer Group in the dropdown on Cash Receipts screen not properly saving change for calling Miscellaneous Cash Receipt Distribution screen.
* Disabled Add button in Misc. Distribution tab when a Customer Group with no Customers is selected.

issue #27813 Cleaned up bugs in Customer Group feature

---

scriptapi/engineevaluate.cpp
scriptapi/engineevaluate.h
scriptapi/qbytearrayproto.cpp
scriptapi/qdnsdomainnamerecordproto.cpp
scriptapi/qdnsdomainnamerecordproto.h
scriptapi/qdnshostaddressrecordproto.cpp
scriptapi/qdnshostaddressrecordproto.h
scriptapi/qdnslookupproto.cpp
scriptapi/qdnslookupproto.h
scriptapi/qdnsmailexchangerecordproto.cpp
scriptapi/qdnsmailexchangerecordproto.h
scriptapi/qdnsservicerecordproto.cpp
scriptapi/qdnsservicerecordproto.h
scriptapi/qdnstextrecordproto.cpp
scriptapi/qdnstextrecordproto.h
scriptapi/qnetworkreplyproto.cpp
scriptapi/qnetworkreplyproto.h
scriptapi/qnetworkrequestproto.cpp
scriptapi/qnetworkrequestproto.h
scriptapi/qtimerproto.cpp
scriptapi/qtimerproto.h
scriptapi/qtsetup.cpp
scriptapi/qtsetup.h
scriptapi/scriptapi.pro
scriptapi/setupscriptapi.cpp

Found some issues when working on Address Verification.
1. Add `global.engineEvaluate()` to Qt Script so we can load javascript code from outside of `pkgscript` tables and have it still showup in Qt Script Debugger. This is for js library code that doesn't have anything to do with our window scripting. It avoids name collisions and prevent the loading of multiple scripts you get with `include('foo')`.
2. Expose all the `QDnsFoo` objects so we can do `dns.lookup`.
3. Expose `QNetworkReply::NetworkError` enum.
4. Fix `QNetworkReply.rawHeader()` bug so it actually returns.
5. Expose `QNetworkRequest::foo` enums.
6. Expose `QTimerProto::setTimerType`, `QTimerProto::timerType` and `Qt::TimerType` enum

Network fixes

---

guiclient/copyItem.cpp
guiclient/copyItem.h
guiclient/copyItem.ui

This commit addresses a race condition.  When selecting an available item number for the new item, the number was being selected within a transaction block.  Until it was committed, other users could select the same item number.  The attempt to find a number by appending an integer to it was not sufficient.
In this proposed solution, I split the copy process into two steps.  After identifying what item to copy, the user must first enter an item number and click "Next".  A database call immediately checks if the item number is available before creating the new item.  When the new item is created successfully, that item exists in the database, and the number can be found by other users.  After clicking "Next", the user can decide what children to copy (item sites, BOMs, etc.)
If after …

issue #25125: Refactored copyItem into two steps

---

guiclient/guiclient.cpp
guiclient/guiclient.h

Try to avoid crashes when the Qt 5 desktop client is run by Squish by removing unused code that appears near the top of the stack trace.

issue #27953 - try to avoid crashes

---

guiclient/guiclient.cpp
guiclient/guiclient.h

Remove `_activeWindow` entirely. See https://github.com/xtuple/qt-client/pull/1233

issue #27953 - remove unused class member

---

guiclient/userPreferences.cpp
guiclient/userPreferences.ui
widgets/xtreewidget.cpp

The root cause of this issue is that the number of bytes needed to perform the copy of the rich data to the clipboard was exceeding the amount of memory addressable by a 32 bit integer, thus causing xTuple to crash.  The most straightforward solution would seem to be to build xTuple as a 64 bit binary.
Barring this, I looked for some way to determine how much addressable space was available, but did not find any approach that would work cross-platform.
What is presented here is a work-around that I feel leaves something to be desired but does address the issue.  I introduced a new preference and placed it on the userPreferences screen beside the choice of copying rich or plain text.  The new preference puts an approximate limit how many bytes of data the XTreeWidget is allowed to export …

Issue #22170: Work-around for copy of large number of rows of rich data from XTreeWidget

---

guiclient/woMaterialItem.cpp
guiclient/woMaterialItem.h
guiclient/woMaterialItem.ui

Work Order widget is not clearing when order number is cleared.  Need to raise an issue for this.

Issue #27345: WO Material Item enabled save inappropriately

---

guiclient/creditcardprocessor.cpp

Removed `QSslCertificate::isValid()` use in builds using Qt5 or above.

Removed deprecated method call for Qt5

---

scriptapi/qhostaddressproto.cpp
scriptapi/qtcpserverproto.cpp
scriptapi/qtcpserverproto.h

Ran into an issue in linux with dashboards and notices we're missing the other non-string constructors here.
https://doc.qt.io/qt-5/qhostaddress.html

Expose additional QHostAddress constructors to Qt Script.

---

scriptapi/qhostaddressproto.cpp

This now works correctly for:
```
var strAddr = QHostAddress('127.0.0.1');
var enumAddr = QHostAddress(QHostAddress.LocalHost);
var intIPAddr= QHostAddress(strAddr.toIPv4Address());
var objAddr = QHostAddress(strAddr);
```

Fix QHostAddress constructor conversions.

---

guiclient/display.cpp
guiclient/display.h

Buttons are hidden by default. To enable In C++ display class window:
`setExpandVisible(true);`
`setCollapseVisible(true);`
In QtScript:
`mywindow.setExpandVisible(true);`
`mywindow.setCollapseVisible(true);`

Issue #28134: Add expand/collapse buttons to display class controllable from C++ and script

---

guiclient/apOpenItem.cpp
guiclient/arOpenItem.cpp

#28292 Remove ability to edit memo amounts AFTER document has been posted.

Issue #28110 #28292: Resolve display of tax on AR/AP memos (after posting)

---

scriptapi/qmenubarproto.cpp
scriptapi/qmenubarproto.h
scriptapi/scriptapi.pro
scriptapi/setupscriptapi.cpp

This allows you to use GUIClient::menuBar(), since prior to this it would error out complaining about needing QMenuBar* registered to the script engine. 
This allows for scripts like:
```
var mb = mainwindow.menuBar();
var accntact;
var kids = mb.findChildren("", 0);
for (var i = 0; i < kids.length; i += 1) {
if (kids[i].toString().indexOf("QMenu") >=0) {
var actions = kids[i].actions();
for (var a = 0; a < actions.length; a += 1) {
if (actions[a].toString().indexOf("Account") >= 0) {
accntact = actions[a];
}
}
}
}
if (accntact) {
var rentalsMenu = new QMenu("R&entals", mb);
rentalsMenu.objectName = "menu.rental";
var rentalContractMenu = new QMenu("&Contract", rentalsMenu);
rentalsMenu.addMenu(rentalContractMenu);
var action = rentalContractMenu.addAction("&New", rentalContractMenu); …
```

Expose QMenuBar to script

---

common/xtuplecommon.h
guiclient/guiclient.h
widgets/widgets.h

Created common/xtuplecommon.h.
-Contains definition and default value for SIGTRACK macro.
-Contains definition and default value for FUNTRACK macro.
-Contains definition for TATTLE macro.
Added include statement for xtuplecommon.h to guiclient.h
Added include statement for xtuplecommon.h to widgets.h

Sigtracker

---

scriptapi/qbuttongroupproto.cpp
scriptapi/qbuttongroupproto.h
scriptapi/scriptapi.pro
scriptapi/setupscriptapi.cpp

Created a scripting API for QButtonGroup.  The specific case where we needed scripting exposure of this class is on the customer workbench, namely the settingsButtonGroup.  For context, this is an issue we created in order to have a branch against which to contribute the change back.
Since this issue is not yet assigned to paladin, I was not able to make any updates to the incident in dogfood.

Issue28345: Created a scripting API for QButtonGroup

---

guiclient/workOrderMaterials.cpp
widgets/woCluster.cpp
widgets/wocluster.h

Also fix a similar manifestation with very different cause in `workOrderMaterials`. That was **really** confusing!

issue #26919 - allow inheritance to work => signals emit more reliably

---

guiclient/cashReceipt.cpp

Now that Card on File has switch to use the old `A`, `D`, `M` and `V` fundstypes, I have to skip processing the charge through the old Credit Card processor code when the Cash Receipt is being handled by the new Card on File processor. Making sure `_metrics->boolean("CCAccept")` is disabled is how that works.

Skip credit card processing if it's not enabled.

---

guiclient/inputManager.cpp
guiclient/inputManagerPrivate.h

The real fix is a one-liner - change the return type of `ReceiverItem::slot()` to QString. The rest of the changes helped debug the problem.

issue #28517 - no need to convert back & forth

---

guiclient/scripts.cpp

Allows proper interaction with other windows and does not exhibit the behavior of embedding itself in the parent window.

Issue #28327: restore ability to edit multiple scripts

---

widgets/comments.cpp
widgets/comments.h

Be nice if we could squeeze this into 4.10  :+1:

Issue #26504: Add Fixed Asset and Maintenance Order Comments Types

---

widgets/xcombobox.cpp

This change prevents selection of a Purchasing Agent where their user account has been marked inactive.
Still need to go through all the relevant screens and amend what happens if an agent is selected on a document (like a PO) and then is removed as an agent.  Current system does not populate the combobox and defaults to the currently active user so does not retain the original agent.

Issue #28497: Prevent Purchase Agent selection for inactive user accounts

---

widgets/xcombobox.cpp

Reverts xtuple/qt-client#1372
I didn't notice that the PR was against 4_10_x. This is a bit too dangerous to put into a final release after an RC.

Revert "Issue #28497: Prevent Purchase Agent selection for inactive user accounts"

---

guiclient/salesOrder.cpp

Reduces Sales Order Item List query calls from 4 to 1 (in my system) by removing unnecessary signals and also preventing the sSalesOrderUpdated signal from calling itself

Issue #27308: Sales Order query optimisation

---

guiclient/display.cpp

While researching the best way to do this I discovered setShortcuts() is available, allowing two shortcuts set from a QList (instead of my alternative idea to instantiate the shortcuts and use their signals).

Issue #28889: Make search on display class windows respond to both Return AND Enter keys

---

widgets/crmacctCluster.cpp

Resolves issue of duplicated Type columns.
Also found the Vendor Type combo on the search screen never (??) worked so fixed that as well.  The correction can work for other CRM account Types so could be added easily in the future, if desired.

Issue #28753: Vendor search widget bugs

---

guiclient/itemSite.cpp

Test on costing method made standard cost visible if job costing allowed
job cost test set the standard cost radio button instead of the job cost radio button
Update itemSite.cpp

issue #28899 - Standard Cost radio button displayed when not allowed in setup

---

guiclient/item.cpp
guiclient/relocateInventory.cpp

Also resolves bug in Item screen where inactive Items Sites were not listed.

Issue #29119: Dont show inactive items in relocate screen

---

common/storedProcErrorLookup.cpp

requires xtuple/xtuple#2936
For some reason the additional argument from the function is not being added to the storedProcError message so I left that out for the moment.

Issue #19902: CRM Account translatable error messages

---

guiclient/itemAvailabilityWorkbench.cpp

Hide error message if the item is not used in any BOM and hence the item widget on the subform is invalid

Issue #29129: Resolve Item Availability confusing error message

---

guiclient/purchaseOrderItem.ui

Populate and save functions already exist but the ui widget was permanently disabled.

Issue #29130: Allow user override of PO item invUOM ratio

---

widgets/xcombobox.cpp

The crashes came from dereferencing `_x_metrics` when it wasn't initialized. The copious connection failures came from trying to connect signals from the `_guiClientInterface` when _it_ wasn't initialized. It's unclear why either of these would occur in the desktop client's embedded Designer.

issue #9241, issue #29514 - fix designer crashes

---

guiclient/salesOrderItem.cpp

This is a minimal change for 4.10.1: Add an availability check after
changing supply orders, and remove an optimization that tried to
replace a save with an in-line calculation. The in-line calculation
incorrectly assumed that the previous line item qty had always been
saved.

issue #29022 - remove optimizations that gave wrong results

---

guiclient/displays/dspBacklog.cpp

requires xtuple/xtuple#2994
Modified sort order as desired, also added QOH column to make the screen more useful for making order shipment decisions.

Issue #18333: Backlog Screen changes

---

guiclient/salesOrderItem.cpp

- reducing error checking during partial saves eliminates
errors when we know the data are incomplete
- temporarily setting the line item id to -1 while preparing
for the next item lets us skip saving when there's
nothing new to save
These changes are probably unnecessary in 4_11_x because the
performance improvements there reduce the number of database
calls.

issue #29739 - fix regression from fix for issue #29022

---

guiclient/projects.cpp

Default dates were automatically populating for ALL date params causing the screen to no long work without manually removing all the parameters.

Issue #29025: Project List Default Date params

---

guiclient/display.cpp
guiclient/displayprivate.h
guiclient/guiclient.pro

Converted the displayPrivate class to a QObject so it can
accept signal/slot connections. Then added a slot and
tracking variable so we can limit finding and setting the
filter to the first time a window instance is shown.

issue #29385 - only reset default filter on first showEvent

---

guiclient/salesOrderItem.cpp

By checking for non-zero quantity and valid item selection,
we can avoid a few database queries when there's nothing
worthwhile to do and avoid opening the Item Sources window.
Also combined two queries.

issue #29730 - reduce unnecessary db calls and window openings

---

guiclient/expenseTrans.cpp
guiclient/expenseTrans.h
guiclient/scrapTrans.cpp
guiclient/scrapTrans.h
guiclient/transferTrans.cpp
guiclient/transferTrans.h

Before: The Before Qty was not populating unless user "selected" the (already set) WH from the WComboBox. 
After: Added signals to _item so that The Before Qty populates after the ItemCluster value is set.
- expenseTrans
- scrapTrans
- transformTrans

Resolves issue #29933 - unable to post scrap/expense transactions

---

common/storedProcErrorLookup.cpp
guiclient/issueToShipping.cpp
guiclient/maintainShipping.cpp
guiclient/salesOrder.cpp
guiclient/shippingInformation.cpp
guiclient/transferOrder.cpp

https://github.com/xtuple/xtuple/pull/3015
In qt-client, all calls to returnItemShipments are wrapped in a transaction, followed by distributeInventory::SeriesAdjust. I propose that the sole purpose of this was to call postItemlocSeries https://github.com/xtuple/qt-client/blob/4_10_x/guiclient/distributeInventory.cpp#L355. Any and all distribution detail occurs entirely in the database because all nested functions of returnItemShipments that call postInvTrans always pass the invhist_id. 
~~I added postItemlocSeries to returnItemShipments (pr linked above).~~ I added postItemlocSeries to postInvTrans https://github.com/xtuple/xtuple/pull/3015/files#diff-986ae11ec8bee1fa06e1ef93bf5affeaR245. This pr removes the transaction blocks from the return stock methods in:
- issueToShipping.cpp
- …

Support for Sales Order (line item) > Return Stock sans locking

---

widgets/usernameCluster.cpp

Been like this for 7+ years.  Could not find a reason why we were using a broad regexp on username.  Makes more sense to have discrete username matching.

Issue #30008: Incorrect username displaying when user name overlaps

---

guiclient/displays/dspDetailedInventoryHistoryByLotSerial.cpp

Lot is capitalised when created so applying this to filter

Issue #30111: Lot selection on inventory history report

---

widgets/virtualCluster.cpp
widgets/virtualCluster.h
widgets/widgets.cpp

Note that to create a useful VirtualCluster you must first create a VirtualClusterLineEdit:
```javascript
// a dumb example
var charle, charcluster;
_charle = new VirtualClusterLineEdit(mywindow, "char", "char_id",
"char_name", "char_mask", "char_notes",
"length(char_name) < 15", "_charle");
_charcluster = new VirtualCluster(mywindow, _charle, "_charcluster");
_layout.addWidget(_charcluster, 2, 0);
```

issue #28349 - allow scripts to create virtual clusters & vc line edits

---

common/metricsenc.cpp

@gilmoskowitz 
I noticed that `load()` has the `_key`, but `set()` doesn't.
```
SELECT setMetricEnc('CCLogin', 'asdf', NULL);
SELECT setMetricEnc('CCPassword', 'asdf', NULL);
SELECT setMetricEnc('CCProxyLogin', 'asdf', NULL);
SELECT setMetricEnc('CCProxyPassword', 'asdf', NULL);
SELECT setMetricEnc('CCYPStoreNum', 'asdf', NULL);
SELECT setMetricEnc('CCPTDivisionNumber', 'asdf', NULL);
```
When `Metricsenc::set()` is called, it's calling the parent `Parameters::set()`, which then calls `Parameters::_set()`, not the child's  `Parametersenc::_set()` because it's `protected` and the parent doesn't have access to it or the `_key`.
I _think_ this will work, but there might be a better solution.

Issue #30138: Metricsenc.set() could not access _key through protected _set.

---

guiclient/voucher.ui

this fixes a recent inadvertent change to the voucher window.
manifestation: documents attached to a voucher in previous versions
are not visible, while documents attached to a voucher in versions
with this bug are stored incorrectly (empty source type)

issue #30363 - fix empty voucher documents tab

---

guiclient/displays/dspTimePhasedOpenAPItems.cpp
guiclient/displays/dspTimePhasedOpenAPItems.h
guiclient/displays/dspTimePhasedOpenARItems.cpp
guiclient/displays/dspTimePhasedOpenARItems.h

Allows scripts to activate the parameterWidget() and pass these to metaSQL

Allow AR/AP Aging to process parameterWidget params

---

guiclient/printCreditMemo.cpp
guiclient/printCreditMemo.h
guiclient/printCreditMemos.cpp
guiclient/printCreditMemos.h
guiclient/printInvoice.cpp
guiclient/printInvoice.h
guiclient/printInvoices.cpp
guiclient/printInvoices.h
guiclient/printMulticopyDocument.cpp
guiclient/printMulticopyDocument.h

There are 6 `printMulticopyDocument.cpp` inherited classes that set `_distributeInventory = true`, which if set will `DistributeInventory::SeriesAdjust`. I added a new method `distributeInventory` to printMulticopyDocument and then call it if `_distributeInventory`.

issue #22868 - remove LAST of remaining distribution locking (printMulticopyDocument.cpp)

---

guiclient/vendor.cpp
guiclient/vendor.ui

Turned off Accounting tab for NEW mode as the data is not relevant.  Also modified text from Check to Payment for consistency across the application.

Issue #30472: New Vendor displayed all vendor details under accounting

---

guiclient/user.cpp
guiclient/user.ui

Would be nice to pass user account username to the employee screen when selecting New Employee from the widget but not sure if that is possible.
Also correctly set default user locale

Issue #30434: User account screen display issues

---

guiclient/issueToShipping.cpp

Issue line or issue all was creating a zero balance shipment if the SO had already been shipped without any errors or message.

Issue #30299: Prevent zero balance shipment when already shipped.

---

guiclient/packingListBatch.cpp
widgets/salesOrderList.cpp
widgets/salesOrderList.h

Make consistent with displayed list.  The SO List will now also exclude fully shipped order lines.  This only applies when accessing from the Packing List Batch screen.

Issue #29304: Make SO selection on Packing List Batch screen consistent

---

guiclient/apOpenItem.cpp
guiclient/apOpenItem.h
guiclient/apOpenItem.ui
guiclient/miscVoucher.cpp

Found a bunch of issues when investigating.  Corrected opening of APOpenItems screen, corrected opening of Misc Voucher screen. Tidied up a bunch of old rubbishy code.  
Possibly need to look into AR Open Items screen as this sometimes duplicates the AP screen logic.

Issue #29225: APOpenItems screen did not open voided item correctly

---

guiclient/financialLayoutColumns.ui

Tried completing functionality (which worked) but these screens are modal so sat over the report edit ui.  So removed button instead.

Issue #29166: Edit button not functional in Financial Reports screen

---

guiclient/returnAuthorization.cpp
guiclient/returnAuthorizationItem.cpp

1. Instead of disabling Recv/Ship Site comboboxes on edit, disable them in populate _IF_ qty credited, qty to receive, qty shipped > 0 https://github.com/xtuple/qt-client/pull/1668/files#diff-3ac3613b6d2a8f0f75c982a136e5a64cR954.
2. If Sales Order warehouse does not match the Recv/Ship on RA header, ask user if they'd like to update them to match the SO before proceeding. The default is Yes.
For 2 above, more details about this decision:
- I didn't want to make the combo boxes `allowNull` because Original Sales Order is optional and user should not always be expected to set the WH.
- Without changing to allowNull, there's no way to know if the WH(s) set previous to original SO should take precedence over the SO warehouse. I like asking the User with the default being Yes (update to …

resolves issue #19021 - inconsistency in RAs (receiving site)

---

guiclient/addPoComment.cpp
guiclient/changePoitemQty.cpp
guiclient/reschedulePoitem.cpp
guiclient/unpostedPurchaseOrders.cpp
guiclient/unpostedPurchaseOrders.h

Order locking in our application has many feature gaps. This pr adds locking to all Purchase Order list actions and utilities so that if a user is editing the PO it can not be modified elsewhere. If this approach is OK it can be extended to other order types.

issue #27513 - possible to make changes to order while being edited by another user

---

guiclient/externalCCTransaction.cpp
guiclient/externalCCTransaction.ui

Added label but could not see how this date field was ever being populated.  Should the widget be removed from the screen?

Issue #14206: Credit Card Transaction screen

---

widgets/datecluster.cpp

Resolves entering single month digit (<10) when locale expects MM

Issue #18973: Handle partially entered months for some locale formats

---

widgets/currcluster.h

Reverts xtuple/qt-client#1810
id was already exposed as a function in CurrDisplay, and CurrCluster inherits from CurrDisplay. Adding it as a property as well breaks existing uses of the function.

Revert "Expose currCluster currency id to scripting"

---

guiclient/apWorkBench.cpp
guiclient/displays/dspVendorAPHistory.cpp
guiclient/displays/dspVendorAPHistory.h
guiclient/displays/dspVendorAPHistory.ui

the ap workbench uses a vendorgroup so the embedded vendor history
must do the same to keep pace.
requires xtuple/xtuple#3206

issue #31730 - handle vendor group instead of cluster

---

guiclient/crmaccount.cpp

in which an instance of the CRM Account window mistakenly thinks
a _different_ instance of the window already has this same account
open.
also avoid raising windows that are buried in a modal dialog stack.

issue #32054 - fix a case of mistaken identity

---

guiclient/items.cpp
widgets/xtreewidget.cpp

requires https://github.com/xtuple/xtuple/pull/3245

issue #32496, issue #17968 - sort on user strings and preserve underlying raw codes

---

common/errorReporter.cpp
common/errorReporter.h
common/storedProcErrorLookup.cpp
guiclient/creditcardprocessor.cpp
guiclient/creditcardprocessor.h

Add a new method to C++ ErrorReporter::getQueryStoredProcErrorMsg() that extracts our stored procedure RAISE EXCEPTION format string and calls storedProcErrorLookup() on it. This method support being called from the older style errorMsg() code in creditcardprocessor.cpp that does not use ErrorReporter currently.
Call the new canProcessPaymentGatewayTransaction() function before any payment gateway transaction is processed in creditcardprocessor.cpp.
Needs: https://github.com/xtuple/xtuple/pull/3253

Issue #27306 - credit card preflight checks

---

guiclient/salesOrder.ui

Could not find what changed between 4.10 and 4.11 to make this widget non-editable, but this change fixes the issue.

[32680] Make Ship Via on Sales Orders editable

---

guiclient/itemSite.cpp
guiclient/itemSites.cpp

Also correct SQL error when copying Item Sites over itself (new bug found when testing).

[31856] Copy Items - retain Item site location control settings. 

---

guiclient/glSeries.cpp
guiclient/glSeries.h

If notes are not saved on standard journal, when posting allow user to enter notes manually for that transaction.  Still enforces requirement for notes.  Manual notes posted to GL Transaction.

[31857] Allow manual entry of notes of missing from standard journal

---

guiclient/taxdisplay.cpp

Moving the Tax Breakdown opening code to the taxdisplay widget caused the Order Number field on that screen to be shrunk and misaligned. I have no idea why, but this fixes it.

Fix Order Number field

---

scriptapi/qserialportproto.cpp
scriptapi/qserialportproto.h

Script exposure had open(QIODevice::OpenModeFlag) when it should have been [open(QIODevice::OpenMode)](https://doc.qt.io/qt-5/qserialport.html#open). I do not have a clue what changed to make this only apparent now, as it has worked up until this point. At first I thought it might be with Qt 5.11 but going back to xTuple 4.10.1 it still happens.

Fix QSerialPort open() script exposure to match what QSerialPort actually is

---

guiclient/project.cpp

Also resolved issue #33271 Project Start Date being overwritten with current date
Adds signal in project.cpp to refresh underlying project list

[33447] [33271] Prevent signal from overriding completion date in Project. 

---

common/storedProcErrorLookup.cpp
guiclient/viewCheckRun.cpp

To ensure consistency with other payment types.
requires xtuple/xtuple#3360

[33431] Allow deletion of voided EFT payment even if printed

---

guiclient/salesOrder.cpp

Traced issue to a problem with the `_mode` value which was incorrectly set by a function that required _mode as an input parameter (?!?).  Could not reproduce error after making this change.

[33214] Resolve issue where Sales Order intermittently opens ui form empty

---

guiclient/cashReceipt.cpp
guiclient/cashReceipt.h

Feature allows better user experience when mass entering receipts

[25779] Allow Cash Receipt screen to remain open after save

---

widgets/apopencluster.cpp
widgets/aropencluster.cpp
widgets/contactCluster.cpp
widgets/crmacctCluster.cpp
widgets/documents.cpp
widgets/itemCluster.cpp
widgets/scriptablewidget.cpp
widgets/shiptoCluster.cpp
widgets/virtualCluster.cpp
widgets/xcombobox.cpp
widgets/xlabel.cpp
widgets/xtextedit.cpp
widgets/xtreewidget.cpp

Replaced qobject_casts that always succeeded with qobject_cast calls and
guarded dereferencing of the resulting pointers. Tested by creating a
uiform with the embedded designer that contains every xTuple custom widget

[33559] fix designer crashes

---

guiclient/addresses.cpp

Some of this is already in version 5.0 so we need to watch for conflicts when merging 4.12 into 5.0
requires xtuple/xtuple#3367

[10370] Add Search and Filters to CRM Address List

---

widgets/customerselector.cpp
widgets/vendorgroup.cpp

Resolves loop problem on VendorGroup widget with a user friendly message.  Applied same logic to CustomerSelector widget.  Probably should also look at display search as well.

[17052] Add better handling of regexp searches to widgets

---

guiclient/itemCharacteristicDelegate.cpp
guiclient/salesOrderItem.cpp

Resolve W/O exploded error messages when updating Configured Items on S/Os.
Resolve duplicate "Update Pricing" message when updating configured items.  I removed the price update from the `ItemCharacteristicDelegate` file as it was causing the trigger to fire twice.  This means the price update has to be handled inside the S/O document itself.   If we wanted to add characteristic pricing to other documents, the logic would have to be repeated.

[33714] Fix bugs with S/O Item configured items.

---

guiclient/createLotSerial.cpp

Was only returning the first value from the getAssocLotSerialIds() function to the dropdown.  XComboBoxes require an INTEGER in the id column.

[33736] Resolve Receipt of T/Os with multiple item lots

---

common/login2.cpp

this didn't happen before because the old code used a non-existent signal - textChanged() -
which was recently replaced by textChanged(const QString &)

[33842] the editingFinished signal is safer than textChanged

---

guiclient/createLotSerial.cpp
guiclient/createLotSerial.h
guiclient/item.cpp
guiclient/lotSerialUtils.cpp
widgets/xcombobox.cpp

Also resolves a bunch of bugs around lot/serial on TO Receipts.
Streamlines the process and makes receiving lots on TOs much easier for end-users.
Fixed characteristic/expiry bug
Locks down Lot receipt so you cannot receive more than shipped
requires xtuple/private-extensions#1034

[29272] Streamline lot/serial traceability on Transfer Orders. 

---

guiclient/returnAuthorization.cpp

When entering sales order number, a spurious message about receiving and shipping site was displayed.  This change handles the scenario without the need for user intervention.

Handle scenario causing spurious Return Authorisation message

---

common/exporthelper.cpp
common/exporthelper.h
guiclient/userPreferences.cpp
guiclient/userPreferences.h
guiclient/userPreferences.ui
widgets/exportOptions.cpp
widgets/exportOptions.h
widgets/exportOptions.ui
widgets/widgets.pro
widgets/xtreewidget.cpp
widgets/xtreewidget.h

Added:
- functionality so that user can select any delimiter that he wants
- an editable combobox to  System > Preferences window, with a list of delimiter values from which the user must select a default.
- a window that prompts user to select export file type and delimiter (when applicable)
- ability to manually enter any file extension (in cases where user wants a .tsv or other extension not offered in our list)

[11131] Add CSV support to Export Data Functionality

---

guiclient/salesOrder.cpp

Caused by missing ';'s between SQL calls.  Updated code to split out queries per coding standards.

[33833] Changing Scheduled Dates on Supply Order S/Os caused SQL error

---

guiclient/customer.cpp

the 'new', 'edit' and 'delete' buttons were already being disabled, so there was no need to disable the XTreeWidget. User cannot edit anything, even if an item is double clicked.
On right clicking, the user still has the option to export, or copy to clipboard. Not sure if that should be permitted in View mode

[24368] enable scrolling for customer characteristics in View mode

---

guiclient/contacts.cpp
guiclient/prospect.cpp
guiclient/prospect.h

If a contact is linked to an Account it will create a prospect from the Account details.  However, if a contact is not linked (standalone) no details where passed into the created prospect.  This change pre-populates some of the Prospect fields from the Contact information.  The link between Contact/Prospect/CRM Account is made when the prospect is saved due to CRM Account timing issues.

[33966] Prepopulate Prospect when creating from Contact

---

guiclient/salesOrderItem.cpp

Including extraneous user dialog popups, plus issues entering multiple SO Items in a row (without closing/reopening the SO Item screen)
@gilmoskowitz can you please check this as it reverts a couple of changes you recently introduced.
Should also be upmerged to 5_0_x

Resolve a number of S/O Item signal problems

---

guiclient/configureIM.cpp

Not quite sure why this is a problem now - possibly related to the Qt upgrade to 5.11, but it should have been a problem previously.
Resolved issue when no Shipping Number is entered by defaulting to minimum of 1.
Found a problem when the screen was opened in that the sequence value was not being returned.  Modified to a better method for returning sequence current value and also fixed query column referencing which was returning a blank value.

[34106] Resolve issues with Inventory configuration

---

common/storedProcErrorLookup.cpp
guiclient/voucherItem.cpp

- Only rollback when the user has not saved a voItem yet (_voitemid == -1)
- delete all distributions when rolling back
- check if `Qty to Voucher == 0` or `no distribution items` when saving or canceling
Also added check to postVoucher function in xtuple repo.
-added translations to all exceptions in postVoucher function

[33376]  VoucherItem window mishandles distributions when user cancels Voucher Item

---

guiclient/display.cpp

If setupCharacteristics() is called more than once in a screen or script, duplicate column errors occur.  This is needed in the Inventory Days package where we rebuild the list columns before each fillList() due to variable columns based on filter selection.
Minor change that checks whether the arrays already contain the characteristic and appends if they do not.
Might need porting back to 4.12 depending on customer requirement.

Minor tweak to display to allow setupCharacteristics multiple times

---

widgets/usernameCluster.cpp

Edit privileges were not being set correctly, therefore virtualClusterLineEdit disabled the 'open' menu action

[32178] 'Open...' not active on Owner field in Account window

---

widgets/docAttach.cpp

This bug only occurred when `Save to Database` was checked. The `setPath()` function would produce a null value for the url value causing the exception.

[33827] Attaching file from UNC path raises DB exception

---

guiclient/main.cpp
widgets/widgets.cpp
widgets/xtupleplugin.h

This allows the Batch Manager in xTuple Connect to build with both 4_12_x and 5_0_x branches of qt-client.

make initializePlugin backwards call-compatibile

---

guiclient/address.cpp
guiclient/address.h
guiclient/address.ui
guiclient/contact.cpp
guiclient/vendor.cpp
guiclient/vendor.ui
guiclient/vendors.cpp
widgets/addressCluster.cpp
widgets/addresscluster.h

MaintainVendorAddresses priv was not being applied outside of the Vendor screen.  Also tidied up ViewVendorAddresses which also did not seem to do much.
Plus various screens could be accessed from the Address uses list in edit mode without appropriate privileges.

[30544] Vendor Addresses could be altered without privs

---

guiclient/displays/dspDocuments.cpp
guiclient/salesOrder.cpp
widgets/docAttach.cpp
widgets/documents.cpp

Document number was inconsistent between screen (file ID versus assignment ID).
Also found link to Sales Orders not working due to inconsistent set parameter naming, plus file privilege assignment was not refreshing correctly.
requires xtuple/xtuple#3493

[33843] Resolve Documents list numbering, plus other bugs

---

guiclient/salesOrder.cpp
guiclient/shipTo.cpp

This bug was reported in the Distribution Edition, but the fix needs to be applied here as well.
The main fix is in `salesOrder.cpp`. 
The changes in `shipTo.cpp` make sure that if a ship-to is inactive then it can't be the default ship-to

[33615] create sales order without Default Ship To 

---

common/storedProcErrorLookup.cpp

The underlying function returned code zero which was not handled in the errorReporter.
Could do with cherry-picking back to 4.12

Fix Material Return error message when no quantity to return

---

guiclient/display.cpp

Introduces an automatic list of XDisplay list columns into the metaSQL parameters that can be used in MQL queries with the following pattern:
```
WITH _contact AS (SELECT blah from cntct)
SELECT * FROM _contact
WHERE true
<? if exists("search_pattern") ?>
AND ( FALSE
<? foreach("search_fields") ?>
OR <? literal("search_fields") ?>::TEXT ~* <? value("search_pattern") ?>
<? endforeach ?>
)
<? endif ?>
```
This allows the regexp search expression to be applied to all columns in the list without the need to individually specify/maintain columns to search on.

[33322] Enable Regexp search across all fields in XDisplay list

---

widgets/xtreewidget.cpp

Some of the signals with XTreeWidget instead of QTreeWidget as arguments that were supposed to be added way back by https://github.com/xtuple/qt-client/commit/2e8251335f06400d418223cb64fad21073c29618 never actually had their slots connected so they still can't be used in scripts. This finally fixes that.

Add missing connections

---

guiclient/salesOrderItem.ui

After speaking with Jim and Mike, it seems that adjusting the item cost from a sales order creates too many accounting complications regardless of the costing method. The user should not be allowed to edit the cost item at this stage

[33967] product cost not updating to invoice

---

guiclient/voucherItem.cpp

PO Reject records were being updated before the Voucher Item was created.  This follows the same path as Received records and updates once the voitem is saved.
Should be able to directly backport to 4.12

[34506] Resolve incorrect GL postings for manually distributed PO reject

---

guiclient/configureWO.cpp
guiclient/configureWO.ui
guiclient/postMiscProduction.cpp
guiclient/postMiscProduction.ui

[34641] Add config re:required trans date entry
This implements the configuration point for the optional feature allowing the
new Post Misc. Production transaction date field to require the user enter a
value rather than defaulting a value.  By default, this value is false/unchecked
meaning that the new transaction date field is defaulted to the workstation's
current date (mimicking the behavior prior to this feature existing).
[34641] Add trans date field handling
This adds handling for the new transaction date field.  Specifically we manage
the permission checks and whether or not we should default the date depending
on the AlterTransactionDates permission and the RequireMiscProdDataEntry
configuration point.  We perform a sanity check on the date prior to allowing
the user to complete …

Post Misc. Production Backdating issue #34641

---

guiclient/main.cpp

The application segfaults every time you close it, however since it is a GUI application the error isn't noticeable unless you start it from a shell. It is caused by our [debug log handler](https://github.com/xtuple/qt-client/blob/4_12_x/guiclient/errorLog.cpp#L134) using objects from Qt long after that stuff has been destroyed. First it is QDateTime, but then xSettings is next if you comment out the QDateTime usage, and so forth.
At that point in the applications life-cycle we do not need to continue our own message handling, simply adding a call to clear the message handler before final termination prevents the crash.
Sample gdb output below, from before the fix:
```
Thread 1 "xtuple" received signal SIGSEGV, Segmentation fault.
0x00007ffff588f9c6 in QLocale::monthName(int, …
```

Fix segfault at application exit by clearing message handler

---

widgets/addressCluster.cpp

Version 5.0 only - rogue columnspan remained from older code.

[33797] Resolve overlapping widgets in Address Cluster

---

guiclient/employees.cpp

This code was masking an underlying SQL error preventing the deletion of employees.
I originally did not replicate the error in version 4.12 but this was due to my Db not having `xtte` installed.  This change can possibly be backported to 4.12.  Related change to `xtte` package possibly makes this change redundant, but updated the code to current standards regardless.
requires xtuple/xtuple#3595

[34489] Split out Employee deletion SQL

---

guiclient/apOpenItem.cpp
guiclient/apOpenItem.h
guiclient/arOpenItem.cpp
guiclient/arOpenItem.h

Was already releasing when Cancel button pressed but did not when cancelled via X window button.
Issue raised reflected problem with A/P memos but same issue applies to A/R memos

[34294] Correctly release AR/AP memo numbers when cancelling document

---

guiclient/crmaccount.cpp

or lost in a upmerge from 4.12 (??)

[34806] CRM Account Document association was not setting the source type

---

guiclient/enterMiscCount.cpp
widgets/ordercluster.cpp
widgets/ordercluster.h

Added an extra signal to `OrderLineEdit`
Emit new signal whenever `sNewId()` is called

[33965] OrderCluster does not emit the newId(int) signal

---

guiclient/poitemTableModel.cpp
guiclient/poitemTableView.cpp

The column for `vendor_uom` could not be populated using `setData()` because it was flagged as `not editable`.
This would make sense if the column appeared in the quick entry table but it does not. An editor is never created for the column. This ensures that the user cannot edit the `vendor uom` from the UI (which is probably the motivation behind setting the flag for that column in the first place).
Additionally, if there is no `itemsrc` for the item created we default to item's inventory UOM

[9618] populate uom programatically poitem quick entry (poitemtableview)

---

widgets/parameterwidget.cpp

Tested on macOS and Linux.
Hold off merging until someone other than me can confirm this is a real bug.

reduce the spacing in multiselect parameterwidgets on macs

---

guiclient/salesOrderItem.cpp
guiclient/salesOrderItem.h

The additional problems were found when using the NEXT and PREVIOUS
buttons on the Sales Order Item window through kit and enhanced pricing
sublines. Once the window had been put into view mode for the sublines,
the `_mode` variable would get set properly but the various fields
would not get re-enabled.

[34342] backport initial fix and add more

---

guiclient/purchaseOrderItem.cpp

The old code is the result of changes made for [9062]. The comment thread pointed to a requirements doc that mentioned that:
> The quantity and date of a Purchase Order should not be editable if the header is linked to a Sales Order.
However, the code disabled those fields for all Purchase Orders

[33351] *PO Line from WO can't be modified

---

guiclient/purchaseRequest.cpp

The query for updating the `pr_prj_id` column was only present in the `cNew` code but not the `cRelease` code.
Also added an error check if createPr() does not return a valid value

[33304] *Project not saved when releasing planned orders to purchase request

---

guiclient/invoice.cpp
guiclient/invoice.ui

Sets the Customer as the initial data entry widget when creating an Invoice.  Previously no widget was default/initial so forced user to have to click on a widget first before being able to enter _any_ data.

[35168] Set customer widget as initial data entry point in Invoice

---

guiclient/salesOrderItem.cpp

when changing wo dates, the startDate would be set to `wo_startdate + (:dueDate-wo_duedate)` which could be a non work day or an exception. but we never check to see if the new startDate is actually a work date

[30460] properly calculate WO start date whenever due date is changed

---

guiclient/viewCheckRun.cpp

tested related [32113] to make sure that still works

[35203] set() before exec() ensures the dialog is initialized properly
