xtuple/qt-client

common/common.pro, global.pri, guiclient/version.cpp
don't merge until after submodule changes are committed to account for https://github.com/xtuple/openrpt/pull/43 and https://github.com/xtuple/csvimp/pull/15
=> turn off shared library usage and building on mac

guiclient/project.ui
=> Issue #21298 Remove Project Type Null Text for consistency

guiclient/displays/dspShipmentsBase.cpp
=> USPS Tracking

guiclient/purchaseOrder.cpp, guiclient/purchaseOrder.ui
=> issue #20480 add quantity, weight to (Purchase Order line items tab) totals

guiclient/accountingYearPeriods.cpp, guiclient/accountingYearPeriods.h, guiclient/accountingYearPeriods.ui
Added to Fiscal Yea screen to facilitate setting up new Financial years based on the last year.
prerequisite xtuple repo. Db. changes
=> Add Copy fiscal year (and corresponding fiscal periods) 

utilities/rptdiff.sh
also simplified some of the logic that does the real work
=> use git in-place to help generate report diffs

postbooks.spec
This is intended for the 4.8 branch because the intention is to package 4.8.1, the latest stable release.  When 4.9.0 is released then this spec file should be updated (version at the top and changelog at the bottom) and become part of the 4.9 release branch.
Please also see the Fedore Review Request bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1196827
=> Add spec file for RPM packaging

common/login2.cpp
This resolves #446 by performing a simple check to see if the database appears to be a valid xTuple database.
This is accomplished by checking for the presence of a table named "metric" in the "public" schema. If present the login will proceed, if not a friendly message is displayed in place of the PostgreSQL error and the user is returned to the login screen.
This catches the case when a user enters any valid database name registered in the PostgreSQL cluster that is not an xTuple database.
=> Implemented basic xTuple database check at login.

guiclient/poitemTableModel.cpp, guiclient/poitemTableModel.h
Also resolves issues 24408, 18979, 20857
=> Issue #24151: Resolves error when editing PO items via Quick entry

guiclient/company.cpp, guiclient/company.ui, guiclient/configureGL.cpp, guiclient/configureGL.ui
Depends on xtuple/xtuple #2224
=> Issue #20982: Unassigned GL account determination for multi-company scenario

guiclient/salesOrder.cpp
Need to confirm why this line was commented out.
=> Issue #25319: Able to add documents to Sales Order in view mode

guiclient/crmaccounts.cpp
(Customer contribution)
Requires update to crmaccounts-detail.mql metasql
=> Issue #25451: Add Account Type parameter filter to CRM Accounts list

guiclient/accountNumbers.cpp, guiclient/accountNumbers.h, guiclient/accountNumbers.ui
Customer feature contribution.  Requires metasql in xtuple repo PR xtuple/xtuple#2243
=> Issue #25486: Add Chart of Accounts filtering by Type/SubType

guiclient/salesOrder.cpp
Resolve correct release of SO number for Auto with override scenario
Requires PR xtuple/xtuple#2249
=> incident #24642: Resolve correct release of SO number for Auto with overd

scriptapi/qapplicationproto.cpp, scriptapi/qapplicationproto.h
fixes last night's build failure
=> allow building in environments without session management

guiclient/invoice.cpp, guiclient/invoice.h, guiclient/invoice.ui, guiclient/miscVoucher.cpp, guiclient/miscVoucher.h, guiclient/miscVoucher.ui
Add ability to post from within Misc Invoice and Misc Voucher documents.  Significant time saving for users who wish to utilise this feature.
=> Issue #21596: Post Documents in a single step

guiclient/displays/dspBacklog.cpp, guiclient/displays/dspPartiallyShippedOrders.cpp, guiclient/displays/dspSalesOrders.cpp, guiclient/openSalesOrders.cpp
Add parameter filter and display in list
relies on PR xtuple/xtuple#2261
=> Issue #21642: Add Sale Type to Sales Reports

common/login2.cpp
replaces #531 
@davidbeauchamp @xtpclark - do these version numbers look right?
=> issue #25664 - pg version check

guiclient/accountNumbers.cpp
=> Issue #25521 CoA report does not honor filter parameters

guiclient/crmaccount.cpp, guiclient/crmaccount.h, guiclient/customer.cpp, guiclient/customer.h, guiclient/item.cpp, guiclient/item.h, guiclient/vendor.cpp, guiclient/vendor.h
Add user locking to Customer, Vendor, Item, & CRM Account
Requires #659 - which has already been merged into this branch
=> Issue #24940: Add user locking to Customer Edit

guiclient/displays/dspSalesHistory.cpp
=> Issue #24853: Add Class Code parameter to Sales History

guiclient/purchaseOrder.cpp
join shipto_name on purchase orders instead of using the CRMAcct_Name
=> Issue 25734

share/dict/reports.base.ts
refresh translations after merging fix for issue #666
=> Prep for4.9.0 beta

guiclient/distributeInventory.ui, guiclient/locations.cpp
Fixes to Item Distribution Layout.  Update sql in locations screen to metaSQL
=> Fix Distribute layout.  Convert locations sql to metaSQL

guiclient/salesOrder.cpp
Also fixes possibility to post CC payments in any order in View Mode
=> Issue #25765: Prevent ability to post payment on closed Sales Order

postbooks.spec
Attempt to address issues from
https://bugzilla.redhat.com/show_bug.cgi?id=1196827
=> Update RPM spec file for Fedora review issues

guiclient/project.cpp, guiclient/project.h, guiclient/project.ui
Allow both Task and Order Activity reporting from within the project screen.  Also set checkboxes to XCheckbox
=> Issue #21311: Clarify Project reporting within the Project screen

guiclient/itemSources.cpp
Add Vendor Number to Item Sources display and mql
=> i25850_add_vendor_number

guiclient/group.cpp, guiclient/user.cpp
Based on feedback added priv description to Granted side of Roles/User maintenance screens.  Also added Role description for clarity/completeness.
=> Issue #25851: Add priv description to granted area on Roles/Users scr

guiclient/main.cpp
Add warnings for missing (open) fiscal periods and missing exchange rates as these cause errors inside the app if not set properly - as well as causing lockups in the mobile web client.
=> Issue #23905: Additional checks on app startup

guiclient/transactionInformation.cpp, guiclient/transactionInformation.h
Prevent save being triggered if analyze flag was not edited.
Must be considered together with xtuple/xtuple#2318
=> Issue #19160: Edit Inv transactions caused QOH problem with frozen sites

guiclient/invoice.cpp
Refresh list after posting to ensure correct list is displayed.
=> Issue #25862: Correct refresh of Unposted Invioce list when posting Invc

guiclient/lotSerialUtils.cpp
Fix for multiple lot serial characteristics when creating lot/serials.
=> Fix Lot Serial characteristics under remapped char processes

widgets/comment.cpp, widgets/comment.h, widgets/comments.cpp, widgets/comments.h
Please give this change a thorough code review
=> switch from enum to string based document types

guiclient/itemSites.cpp
Requires xtuple/xtuple#2338
Requires xtuple/private-extensions#621
Minor tweak to assist with lot/serial/location refactor project
=> Issue #25914: Add Loc Ctrl parameter to ItemSites screen

guiclient/todoList.cpp
Lots of logic flaws in this file.  Appears to be able to handle all the different scenarios now.
=> Issue #25825: Fix deletion of recurring ToDo parent item

guiclient/main.cpp
Very minor but found it while looking at something else.
=> Fix typo in reference to a metric

guiclient/creditcardprocessor.cpp
Inserts identified with:  grep -irzo "INSERT INTO .\{1,10\} VALUES" .
This will possibly pick up multi-line sql, but not 100% sure
=> Issue #24727: remove blind inserts

guiclient/guiclient.cpp, guiclient/systemMessage.cpp
Also resolves sql bug when creating System-wide message
=> Issue #25286: Make system message non-modal

guiclient/characteristic.cpp
do not merge yet, still testing.
=> add back removed single slash, caused compile error on mac build

guiclient/displays/dspBookings.cpp, guiclient/displays/dspBriefSalesHistory.cpp, guiclient/displays/dspSalesHistory.cpp, guiclient/displays/dspSummarizedSales.cpp, guiclient/openSalesOrders.cpp
=> Issue #20143: Add Customer PO filter to Sales Analysis screens

guiclient/apOpenItem.cpp, guiclient/apOpenItem.h, guiclient/apOpenItem.ui, guiclient/arOpenItem.cpp, guiclient/arOpenItem.ui, guiclient/displays/dspAPOpenItemsByVendor.cpp, guiclient/displays/dspAPOpenItemsByVendor.h, guiclient/guiclient.pro, guiclient/printApOpenItem.cpp, guiclient/printApOpenItem.h, guiclient/printApOpenItem.ui, widgets/apopencluster.cpp, widgets/apopencluster.h, widgets/plugins/apopenclusterplugin.h, widgets/widgets.cpp, widgets/widgets.pro
Requires xtuple/xtuple#2395
TODO Add in printing hooks for xtConnect
=> Issue #25963: Add AP Open Item report and hooks into application

guiclient/displays/dspPricesByItem.cpp, guiclient/priceList.cpp, guiclient/priceList.h, guiclient/pricingScheduleAssignment.cpp, guiclient/pricingScheduleAssignment.ui, guiclient/pricingScheduleAssignments.cpp, guiclient/salesOrder.cpp, guiclient/salesOrderItem.cpp, guiclient/salesOrderItem.h
=> Issue #26223: Pricing by Shipping Zone & Sale Type (initial commit)

guiclient/salesOrder.cpp, widgets/docAttach.cpp
This is the desktop client portion of the fix. See https://github.com/xtuple/xtuple/pull/2444 for the server side. This builds on #807 which should be merged first.
=> issue #26313 - sales order and quote doc ass

guiclient/postCashReceipts.cpp, guiclient/xdialog.cpp
Database changes: xtuple/xtuple#2440
=> Issue #17259: Fix cashrcpt post query

guiclient/invoice.cpp, guiclient/salesOrder.cpp
=> Issue #26338: Correct Invoice Outstanding balance 

guiclient/transferOrder.cpp
Was causing confusion at customer site - erroneous delete msg when saving.
=> Issue 17699: Correct faulty delete msg on new T/O

guiclient/displays/dspOrderActivityByProject.cpp
also resolves display of all invoices when pressing Query
=> Issue #26362: Missing check for project #

guiclient/poLiabilityDistrib.cpp, guiclient/poLiabilityDistrib.ui
Add date to screen and use this date instead of current_date
=> Issue #11922: Enforce entry of Distribution Date on P/O Liability

widgets/characteristicAssignment.ui, widgets/comment.cpp, widgets/comment.h, widgets/virtualCluster.cpp, widgets/warehousegroup.cpp, widgets/warehousegroup.h, widgets/xcombobox.cpp
These problems were revealed or exacerbated by xtdesktop 4.0's changes to the application styling. Please review carefully to make sure no _functionality_ was touched.
=> issue #26269 - various ui refinements

guiclient/accountNumber.cpp, guiclient/accountNumbers.cpp, guiclient/accountingPeriods.cpp, guiclient/accountingYearPeriod.cpp, guiclient/address.cpp, guiclient/adjustInvValue.cpp, guiclient/adjustmentTrans.cpp, guiclient/allocateARCreditMemo.cpp
There IS method to my madness;  I'm working thru the CPP files alphabetically...for lack of a better methodology!
=> 1st Batch of programs: errorReporterRefactor project

widgets/filterManager.cpp, widgets/filterSave.cpp, widgets/parameterwidget.cpp
Database changes at: xtuple/xtuple#2439
=> Issue #23152: Allow to edit/create shared filters based on a privilege

guiclient/enterPoReturn.cpp, guiclient/enterPoReturn.ui, guiclient/enterPoitemReturn.cpp, guiclient/enterPoitemReturn.h
Add Vendor Authorisation #  (RMA) to PO Returns
requires xtuple/xtuple#2479
=> Issue #24158: Add RMA field to PO Returns

guiclient/purchaseOrder.cpp
=> Minor Purchase Order bug

guiclient/glTransaction.cpp, guiclient/glTransaction.ui
=> Issue #26366: Print on Post GL Simple transactions

guiclient/configureGL.cpp, guiclient/configureGL.ui, guiclient/currencies.cpp, guiclient/currencies.h, guiclient/currencies.ui, widgets/comment.cpp, widgets/comments.cpp, widgets/comments.h, widgets/xcombobox.cpp, widgets/xcombobox.h
=> Issue #25986: Add Comments for Exchange Rates

common/login2.cpp
Merge after testing with PG 9.4. If that goes well, we can also mark issue #24342 resolved.
=> issue #26462 - update postgres version checks

guiclient/salesOrderItem.cpp
@garyhgohoos - could you please review this? it looks like the code to be changed moved between 4_9_x and 4_10_x.
=> issue #26610 - backport fix to 4.9.2

guiclient/configureCC.cpp
NOTE:  Only single file in this batch in order to test full workflow
and insure ../openrpt is not getting included in commit/push process.
=> errorReporterRefactor 10/14/15 batch

guiclient/displays/dspInventoryAvailability.cpp, guiclient/displays/dspInventoryHistory.cpp, guiclient/displays/dspQOH.cpp, guiclient/displays/dspUsageStatistics.cpp
=> Issue #26741 and issue #2583: ABC Classification fix and additional reporting

guiclient/vendor.ui
This may have also fixed issue #26742
=> issue #26743 - wrap radio buttons in a frame to create a group

guiclient/printStatementByCustomer.ui, guiclient/printStatementsByCustomerGroup.h, guiclient/printStatementsByCustomerGroup.ui
Fix typo on Statement by Cust Group screen - plus some ui layout fixes
=> Issue #26806: Statements by Customer Group

guiclient/packingListBatch.cpp, guiclient/packingListBatch.ui
Filter Packing List Batch by Hold Status - also display Pack Date (sortable)
Addresses issues 26246 & 7175
requires xtuple/xtuple#2536
=> Issue #26246: Add Pack Date and selectable Hold Status to Packing List Batch

guiclient/employees.cpp
=> Issue #25718: Add Employee Group filter to list

guiclient/project.cpp, guiclient/project.ui
The is the PROPER push/pull request (fixed via git cherry-pick)
=> i26654 projectType xComboBox layout resolved and populate issue resolved

guiclient/distributeToLocation.cpp, guiclient/dspAROpenItems.cpp, guiclient/dspBankrecHistory.cpp, guiclient/dspBillingSelections.cpp, guiclient/dspCashReceipts.cpp
Gil:  Sorry it's so few files but a couple of the dsp....cpp files were 'humdingers' (especially dspAROpenItems.cpp).  I wanted to push them and get any feedback on them while they were 'fresh' in my mind...before plowing on.
=> errorReporterRefactor 11/10/15 Batch

guiclient/vendor.cpp, guiclient/vendor.ui
Linked via CRM account in the same manner as Customer.
=> Issue # 26866: Add documents tab to Vendor master

guiclient/vendor.cpp, guiclient/vendor.h, guiclient/vendor.ui
This fixes Docs, Chars, and Comments but most of the effort is due to Comments link to CRM Account.  This would be vastly simplified if we switched Comments type from CRMA to V.
=> Issue #26813: Handle Comments/Docs/Chars on New Vendor record

guiclient/dspTaxReturn.cpp, guiclient/dspTaxReturn.h, guiclient/dspTaxReturn.ui, guiclient/menuAccounting.cpp, guiclient/taxCode.cpp, guiclient/taxCode.h, guiclient/taxCode.ui
Clarification of purpose of tax code settings based on feedback.
Complete and tidy up Tax Return screen and report.  Provide a simpler report as the detail can be obtained from the existing Tax History reports
requires xtuple/xtuple#2548
=> Issue #26693: Additional clarification and reporting for VAT type taxation

guiclient/creditMemo.ui, guiclient/creditMemoItem.ui, guiclient/unpostedCreditMemos.ui
based on comments/ feedback from @piercetyler 
requires xtuple/qt-client#963
=> Issue #26802: Revert some Sales CM naming

guiclient/displays/displays.pri, guiclient/displays/dspInventoryLocator.cpp, guiclient/displays/dspQOHByZone.cpp, guiclient/displays/dspQOHByZone.h, guiclient/displays/dspQOHByZone.ui, guiclient/menuInventory.cpp, guiclient/menuInventory.h
=> Issue #26950: QOH by Inventory Zone display and reports

guiclient/purchaseOrderItem.cpp
Only calculate freight tax when freight is entered (edge case scenario)
=> Issue #26745: Resolve PO Item Freight tax issue

guiclient/opportunity.cpp
deleteOpportunity() handles removal of Characteristics and Comments on cancelling a new Opp.    Based on previous discussions any Documents added will remain in the system.
=> Issue #26084: Add Chars/Docs/Comments on NEW Opportunity

guiclient/applyAPCreditMemo.cpp, guiclient/unappliedAPCreditMemos.cpp
=> Issue #26973: Convert AP Memo cpp sql into metaSQL

guiclient/itemSite.cpp, guiclient/itemSite.ui, guiclient/itemSites.cpp
Check for existing lot/serial setting when creating Item Site.  User can override if desired.
=> Issue #26705: ItemSite Lot/Serial control on Transfer Orders

common/storedProcErrorLookup.cpp, guiclient/characteristic.cpp, guiclient/characteristic.ui, widgets/characteristicAssignment.cpp, widgets/characteristicAssignment.h
=> Issue #26832: Enforce user definable unique characteristic setting

guiclient/displays/dspBOMBase.cpp
Changed Title of Error Panel as requested by Panduk
=> Incident #26958: Additional Change to Error Panel as requested

guiclient/creditMemoItem.cpp, guiclient/creditMemoItem.ui
=> issue #26811 - fix tab order (and uic warnings)

guiclient/creditMemoItem.ui
replaces #962 - isolate szuke's fix from changes for issue 26811
=> issue #26810 - start on the leftmost tab

guiclient/createLotSerial.cpp, guiclient/distributeInventory.cpp
Resolves passing of lot/serial information between sites on a T/O
=> Issue #26705: Fix Transfer Order transfer of Lot Serial to Receiving Site

guiclient/displays/dspSalesOrders.cpp, guiclient/openSalesOrders.cpp
=> Issue #26699: Additional Sales Order list/search filters

guiclient/incidentWorkbench.cpp
Add priority order to incident workbench
requires xtuple/xtuple#2577
=> Issue #27105 incident priority order

guiclient/transferOrderItem.cpp
Prevent cancelling an unreleased TO item
=> Issue #26981: Transfer Order Item cancellation

guiclient/pricingScheduleAssignment.cpp
NULL <> NULL for some strange reason
=> Issue #26692: Resolve duplicate pricing schedule assignments

guiclient/miscVoucher.cpp, guiclient/miscVoucher.h
Added refresh when Distribution Date is updated
=> Issue #27175: Misc Voucher tax refresh when no Dist Date

guiclient/configureSO.cpp, guiclient/configureSO.ui, guiclient/openSalesOrders.cpp, guiclient/salesOrder.cpp, guiclient/salesOrder.h, guiclient/salesOrder.ui
requires xtuple/xtuple#2578
Configurable S/O credit check on save.  Also enhances Open SO screen to filter/display hold type.
=> Issue #15171: Sales Order Credit  Limit check

guiclient/address.cpp, guiclient/displays/dspQOHByLocation.cpp, guiclient/displays/dspQOHByLocation.h, guiclient/guiclient.cpp, guiclient/guiclient.pro, guiclient/inputManager.cpp, guiclient/inputManager.h, guiclient/inputManagerPrivate.h
This is a first pass at replacing functions with data to scan smart bar codes. The next step is to drive this mechanism from a database table, allowing extensions to add their own smart bar codes.
=> issue #26994 - reduce redundancy in smart bar code handling

guiclient/displays/dspGLTransactions.cpp
requires xtuple/xtuple#2582
Parameter does not appear to do anything in this report (or Summarised GL Trans)
=> Issue #25978: Fix GL Transactions report

guiclient/customer.cpp
@garyhgohoos: Please review this carefully. The changes look innocuous which worries me - What essential work is _not_ going to happen?
Tested in both Customer and Workbench modes with no apparent problems.
=> issue #27282 - reduce the work done when saving customers

guiclient/salesOrder.cpp
=> Issue 15171: Only change hold status if saving SO

guiclient/priceList.cpp, guiclient/priceList.ui, guiclient/salesOrder.cpp
Also found SO Item list ignored privilege
=> Issue #27230: Unit costs visible on SO despite not having privileges

guiclient/invoiceItem.ui
Been annoying me for ages this one.
=> Fix Invoice Item tab order

guiclient/vendor.cpp
Default vendor screen to general page
=> Issue #27172: Vendor screen behaviour

guiclient/authorizedotnetprocessor.cpp
The format of Authorize.Net card-present (CP) and card-not-present (CNP) responses is different. We cannot really support CP transactions yet but let's try to do something reasonable if we happen to get one.
It may not be possible to test the CP case but at least we can regression-test the CNP. Manual dev testing of CP was done by setting a field in the C++, testing, then removing that extra line.
=> issue #27156 - a.n card-present and -not-present have different fields

guiclient/projects.cpp
=> Issue #27358 Project List Searchable characteristics missing

guiclient/openPurchaseOrder.cpp, guiclient/openReturnAuthorizations.cpp, guiclient/openSalesOrders.cpp, guiclient/opportunity.cpp, guiclient/opportunityList.cpp, guiclient/opportunitySource.cpp, guiclient/opportunityStage.cpp, guiclient/opportunityType.cpp
All the way from "A" thru "O".  Getting closer to the end!
=> errorReporterRefactor Batch 01/22/16

guiclient/returnAuthorizationWorkbench.cpp
=> issue #26638 - backport to 4.9.3

guiclient/salesOrderItem.cpp
=> issue #26643 - backport to 4.9.3

guiclient/createLotSerial.cpp, guiclient/itemSite.cpp, guiclient/itemSite.ui, guiclient/itemSites.cpp
accompanies xtuple/xtuple#2609
=> issue #26705 - backport to 4.9.3

guiclient/main.cpp
backporting to accompany other registration-related changes
=> issue #26844 - backport to 4.9.3

widgets/documents.cpp
=> issue #26887 - backport to 4.9.3

guiclient/incidentWorkbench.cpp
=> bug #27105 - backport to 4.9.3

guiclient/displays/dspTimePhasedUsageStatisticsByItem.cpp
=> Issue #27158 Add missing inventory transactions to Usage screen/reports

guiclient/purchaseRequest.cpp
Reinstate saving of Project on new PR
=> Issue #27473: Fix save of Project for new Purchase Requests

guiclient/reschedulePoitem.cpp, guiclient/reschedulePoitem.h, guiclient/reschedulePoitem.ui
Functionality to reschedule all open items on a PO
=> Issue #12607: Allow reschedule of all (open) items on a P/O

guiclient/apOpenItem.cpp, guiclient/arOpenItem.cpp, guiclient/dspTaxHistory.cpp, guiclient/dspTaxReturn.cpp, guiclient/miscVoucher.cpp, guiclient/taxAssignment.cpp, guiclient/taxAssignment.h, guiclient/taxAssignment.ui, guiclient/taxCode.cpp, guiclient/taxCode.h, guiclient/taxCode.ui, guiclient/voucherMiscDistrib.ui
Tidy up AR/AP Memo approach. 
#27338: European VAT Reverse Charges functionality
requires xtuple/xtuple#2648
=> Issue #27338: VAT Reverse Charges and other taxation improvements

common/storedProcErrorLookup.cpp, guiclient/configureIM.cpp, guiclient/configureIM.ui, guiclient/issueToShipping.cpp
User prefs were overriding the cpp code so prevent user prefs from being applied.
=> Issue #27694: Override user prefs on Require Sufficient Inventory

guiclient/dspAROpenItems.cpp
Resolve issue found on customer site
=> Resolve custom parameters processing in dspAROpenItems display

guiclient/packingListBatch.cpp, guiclient/warehouse.cpp, guiclient/warehouse.ui
requires xtuple/xtuple#2654
requires xtuple/private-extensions#751
Default PickList added to Transit Site and picked up when shipping T/O.   Sample T/O Picklists added to private extensions.
=> Issue #26322: Transfer Order Picklist

guiclient/adjustmentTrans.cpp
Gil:  First push for guiErrorCheckRefactor to make sure the entire 'flow' is working properly.
=> guiErrorCheckRefactor 1st Push

guiclient/invoice.cpp
Check edited recurring invoices and ask user if they want edited invoice to become new template for recurrence.
Also fixes bug when editing recurring, posted invoice
=> Issue #21351: Allow updating of recurring invoices details

guiclient/menuSystem.cpp
Changed urls for Marketplace and Blogs in the Help Menu.
=> issue #27581 Menu link update

guiclient/workOrder.ui
Clarify difference between WO Item chars and WO specific chars
=> Issue #27366: WO specific characteristics

guiclient/salesOrder.cpp, guiclient/salesOrder.h
Resolve logic issue so that users with OverrideSOHoldType privilege can override the automatic credit check
=> Issue #15171: Sales Order Credit Checks

scriptapi/addressclustersetup.cpp, scriptapi/addressclustersetup.h, widgets/contactwidget.h
Also exposes AddressCluster* to the script engine.
=> Issue #27779: Expose the embedded AddressCluster inside ContactWidget

guiclient/miscVoucher.cpp, guiclient/voucher.cpp
for MSA project
requires xtuple/xtuple#2670
voucher and miscVoucher now use the same metaSQL logic for their respective Misc. Distributions tabs
=> Issue #27780:  Convert Voucher and MiscVoucher to utilise metaSQL

guiclient/configureSO.ui, guiclient/creditMemo.ui, guiclient/dspAROpenItems.cpp, guiclient/printCreditMemos.ui, guiclient/reprintCreditMemos.ui, guiclient/unpostedCreditMemos.cpp
plus resolve bug in unpostedCreditmemo screen found during testing
=> Issue #26802: Further Sales Credit label changes after initial testing

guiclient/displays/dspSlowMovingInventoryByClassCode.cpp, guiclient/displays/dspSlowMovingInventoryByClassCode.ui
=> Issue #27357: Add tolerance level to Slow Moving Inventory

guiclient/currencies.ui
=> Issue #27743: Exchange Rate Comments - add label

guiclient/printCreditMemo.ui
=> Issue #26802: Sales Credit labels

debian/changelog, guiclient/Info.plist, guiclient/version.cpp, utilities/doxygen/Doxyfile.public
=> Updated version numbers

guiclient/itemAlias.cpp
requires https://github.com/xtuple/xtuple/pull/2682
=> Issue #27836:include itemalias_crmacct_id in unique constraint

guiclient/configureSO.cpp, guiclient/copyBudget.cpp, guiclient/copyItem.cpp, guiclient/correctProductionPosting.cpp, guiclient/country.cpp, guiclient/createItemSitesByClassCode.cpp, guiclient/createLotSerial.cpp, guiclient/createPlannedOrdersByItem.cpp, guiclient/createPlannedOrdersByPlannerCode.cpp, guiclient/creditMemo.cpp, guiclient/currencyConversion.cpp, guiclient/customerGroup.cpp, guiclient/customerType.cpp
FINALLY!!!!! back to work on the project.  Got buried with a SAGE 100 project that derailed me from working on this project for awhile.  Back in the harness now!   :-)
=> guiErrorCheckRefactor 04/27/16 Batch

guiclient/item.cpp
Managed to reuse existing metaSQL 
Requires xtuple/xtuple#2704
=> Issue #27868: Migrate Item lists to MetaSQL to enhance customisation

guiclient/displays/dspUserPrivileges.cpp, guiclient/menuSystem.cpp
Could be a little confusing and mistaken for a maintenance screen.
=> Tidy up (clarify) user privilege screen

guiclient/configureIM.cpp
Could not save Setup option due to incorrect IF statement
=> Issue #27965: Resolve TO Shipping Interface Setup screen not working

guiclient/userPreferences.cpp
Issue was with maintainPreferencesOther allowing blanket access to the screen.  Resolved logic flaw so privileges work independently.
=> Issue #27964: Resolve privileges issue with user settings

guiclient/displays/dspTimePhasedSales.cpp
Use saleshistory views
requires xtuple/xtuple#2712
=> Issue #27584: Time Phased Sales inconsistent with other sales reports

guiclient/reassignProductCategoryByProductCategory.cpp
=> issue #27911 - trim pattern and modernize the surrounding code

guiclient/dspTaxHistory.cpp
plus minor improvements based on beta testing feedback
requires xtuple/xtuple#2723
=> Issue #28027: Resolve VAT issues in Tax History report 

guiclient/customers.cpp, guiclient/customers.h
=> Issue #28049: Add Hold Status to Customers Display and parameters

guiclient/todoCalendarControl.cpp, guiclient/todoListCalendar.cpp, guiclient/todoListCalendar.h
Display both ToDo items and Project Tasks on the Calendar display screen
=> Issue #28146:  Add project tasks to Calendar ToDo Listing

guiclient/voucher.cpp, guiclient/voucher.ui
Could add Misc Distributions when in view mode
=> Issue #28057: Resolve being able to add misc distributions on Vouchers

guiclient/todoListCalendar.cpp
Altered columns had caused this screen to break.  Modified to make more robust for future column additions
=> Issue #16481: ToDo Calendar broken links to Customer

guiclient/workOrder.cpp
=> Issue #28238: Convert WO detail to metasql

guiclient/scriptEditor.cpp, guiclient/scriptEditor.h, guiclient/scripts.cpp
Nothing would stop you from opening the same script more than once, should I modify the window to use AppLock?
=> issue #28327 - allow multiple scripts to be edited at once

guiclient/accountNumber.cpp
after switching either setting off
=> Issue #28303: Fix population of profit center / sub-account 

guiclient/createfiscalyear.cpp, guiclient/createfiscalyear.h, guiclient/createfiscalyear.ui, guiclient/guiclient.pro, guiclient/main.cpp
=> issue #22870 - simplify config when missing accounting periods

guiclient/itemSources.cpp
needs xtuple/xtuple#2785 to be useful
=> issue #28338 - support the search box

guiclient/customer.cpp
also fix 1 compiler warning and 1 line length violation
=> issue #28331 - check whether custtype changed before asking about charass

guiclient/databaseInformation.cpp, guiclient/main.cpp
and minor code simplifications
requires xtuple/xtuple#2792
easiest to review [ignoring whitespace changes](https://github.com/xtuple/qt-client/pull/1343/files?w=1)
=> issue #28306 - use unified getEdition function

scriptapi/setupscriptapi.cpp, widgets/itemgroupcluster.cpp, widgets/itemgroupcluster.h, widgets/plugins/itemgroupclusterplugin.h, widgets/widgets.cpp, widgets/widgets.pro
=> Issue #28427: Add item group cluster, update widgets.pro to be Qt5 compatible 

guiclient/databaseInformation.cpp, guiclient/main.cpp
commit comment has wrong issue number
=> issue #28415 - don't break on older databases

guiclient/arOpenItem.cpp, guiclient/cashReceipt.cpp, guiclient/dspCashReceipts.cpp, guiclient/salesOrder.cpp, guiclient/salesOrderSimple.cpp
Needs: https://github.com/xtuple/xtuple/pull/2806
=> Issue #27022 Card on File support. Add fundstype type, helper functions and use them

guiclient/splitReceipt.cpp, guiclient/splitReceipt.ui, guiclient/voucherItem.cpp, guiclient/voucherItem.h
removed transaction and fixed split freight functionality
=> issue #28280 - Removed transaction block from voucherItem and fixed split receipt freight

widgets/crmacctCluster.cpp
Was focused on the search window the first time and totally ignored List.
=> Issue #18335: Resize windows to something reasonable, now including the List window

guiclient/taxBreakdown.cpp, guiclient/voucher.cpp, guiclient/voucher.h, guiclient/voucherItem.cpp
and screen display issues
requires xtuple/xtuple#2824
=> Issue 28456: Resolve some residual VAT Taxation bugs, features

guiclient/salesOrderSimple.cpp
(cherry picked from commit 805f83b575df0654ac2cdcad101829455ec95de5)
=> Properly initialize tax zone

guiclient/salesOrderItem.ui
(cherry picked from commit 002954e9e77eeb304e76ecb79cd2958bd2b3413f)
=> issue #28583 - Fixed tab order

guiclient/postProduction.cpp
(cherry picked from commit 282ae87e2bd81573b8aafd3b2dee6bd94e9970cb)
=> issue #28526 - passing the right time is the client's job

guiclient/workOrder.cpp
(cherry picked from commit 38c398ff0ca57bddb15c9f14681af66678e7614a)
=> issue #28553 - don't ignore operations if on a different tab

guiclient/customer.cpp
(cherry picked from commit a038d08e90957fdfb86db16f9d1e43771131fbbb)
=> issue #28569 - Don't detect new customer as duplicate after partial save

guiclient/configurePD.cpp, guiclient/configurePD.ui, guiclient/item.cpp
=> Issue #28616: Enforce unique UPC Codes (Product configuration)

common/applock.cpp
(cherry picked from commit 275cf0552aec7cce05cf2ac17d496875edd58abe)
=> issue #28711 - backport - Fix broken joins in query

guiclient/creditMemo.cpp
(cherry picked from commit 795af62c908a10d101911b32986246fcf85fe667)
=> issue #28698 - backport - Rearrange order to prevent trigger error

widgets/comments.cpp, widgets/comments.h
(cherry picked from commit 0e51bd7e783689a69bcd9459475335d56dcfb78d)
=> issue #26504 - backport - Fixed Asset and Maintenance Order Comment types

guiclient/inputManager.cpp
=> Issue #28616: Minor tweak to only return UPC Code from active items

guiclient/menuSales.cpp, guiclient/updatePrices.cpp, guiclient/updatePrices.h
make the dialog modal and simplify the code
=> issue #28752 - prevent multiple window instances from sharing a temp table

guiclient/guiErrorCheck.cpp, guiclient/guiErrorCheck.h, guiclient/guiclient.cpp, scriptapi/setupscriptapi.cpp
Sample Script:
var list = {};
list[0] = GuiErrorCheck(1 == 2, mywindow, "This is an error");
list[1] = GuiErrorCheck(1 == 1, mywindow, "This is not an error");
var hasErrors = GuiErrorCheck.reportErrors(mywindow, "Error Check", list);
=> Issue #28763: Expose guiErrorCheck to script

guiclient/woMaterialItem.cpp
(cherry picked from commit 36d2f262438cf455a2e7a885635cfc6c40fe6480)
=> issue #27345 - backport - Clear item fields when item is cleared

guiclient/guiclient.cpp
(cherry picked from commit 1e70f4ceb9fffe86f9d0dd9fa6eadc1c7dac287a)
=> issue #28811 - backport - rm xtcore union now that it's in pkghead

guiclient/inputManager.cpp
(cherry picked from commit 8e4774d5f5b4cf505951b42708cd4eb01c3bffda)
=> issue #28736 - backport - Fixed keyboard lock

guiclient/unappliedARCreditMemos.cpp, guiclient/unappliedARCreditMemos.h, guiclient/unappliedARCreditMemos.ui
=> Issue #28859: Add Customer filter to Unapplied CM screen

guiclient/displays/dspQOHByLocation.cpp
requires xtuple/xtuple#2883
Resolves multi warehouse error in Postbooks systems
=> Issue #28843: Postbooks error in QOH By Location report due to multiwhs

guiclient/createLotSerial.cpp
Uses charuse assignment as the 'active' flag
=> Issue #28866: Resolve inactive Lot Serial characteristics

guiclient/displays/dspWoSchedule.cpp
requires new function woplancost and changes to workorderschedule in https://github.com/xtuple/xtuple/pull/2890 and https://github.com/xtuple/xtuple/pull/2896
=> issue #28730 - add wip value to wip schedule

guiclient/cashReceipt.ui
correct alignment of project widget
=> Issue #28304: Cash Receipt project widget alignment

guiclient/adjustmentTrans.cpp
(cherry picked from commit bf11ade7fbb6962a2c4d4dabe83c58f474df75de)
=> issue #28634 - end transaction when error is thrown

guiclient/configureGL.cpp
=> Issue #28298: Add alert if selected ACH batch number is less than

guiclient/arWorkBench.cpp
(cherry picked from commit c978546b3ebbd63fda235696d75d8c4f1b59d9fc)
=> issue #28851 - Fix ErrorReporter call

guiclient/setup.cpp
=> issue #28915 - hack to hide workflow option in setup side-menu

guiclient/locations.cpp
plus fix missing zone filters
requires xtuple/xtuple#2905
=> Issue #28020: Resolve discrepancy in Location report 

guiclient/customer.cpp
Resolve sales history on customer workbench, plus switch to metaSQL
to allow alternate sales history calculations (i.e. fiscal year)
requires xtuple/xtuple#2906
=> Issue #27500: Customer Sales History

common/storedProcErrorLookup.cpp, guiclient/configurePD.cpp, guiclient/configurePD.ui, guiclient/miscVoucher.cpp, guiclient/voucher.cpp, guiclient/voucher.h, guiclient/voucher.ui, guiclient/voucherMiscDistrib.cpp, guiclient/voucherMiscDistrib.h, guiclient/voucherMiscDistrib.ui, widgets/plugins/voucherclusterplugin.h, widgets/voucherCluster.cpp, widgets/voucherCluster.h, widgets/widgets.cpp, widgets/widgets.pro
Freight distribution to PO Voucher Items
Also resolves #26390 and probably other issues
requires xtuple/xtuple#2924
=> Issue #26765 Landed Cost

common/storedProcErrorLookup.cpp, guiclient/items.cpp
=> Issue #28994: Prevent deletion of item if used on an invoice

common/storedProcErrorLookup.cpp, guiclient/displays/dspWoSchedule.cpp, guiclient/postMiscProduction.cpp, guiclient/purgeClosedWorkOrders.cpp, guiclient/returnAuthorizationItem.cpp, guiclient/salesOrderItem.cpp, guiclient/workOrder.cpp
Plus update error message handling to current approach.
requires xtuple/xtuple#2932
=> Issue #28546: Prevent deletion of WO if WIP on the order

guiclient/itemSite.cpp, guiclient/itemSite.h
=> Issue #29110: Prevent setting control method to None when Item Site

guiclient/selectPayments.cpp
=> Issue #28962: Add On Hold Comment to AP Payment screen

guiclient/poitemTableModel.cpp, guiclient/poitemTableModel.h, guiclient/poitemTableView.cpp
requires xtuple/xtuple#2948
Update PO Item Quick Entry to handle taxation type.  This resolves another issue regarding taxation of non-inventory PO items (expense categories).
=> Issue #29274 Purchase Item Tax Type handling

guiclient/configureSO.cpp, guiclient/configureSO.ui, guiclient/openSalesOrders.cpp
Defaults to the current -90 days if metric not set.
=> Issue #29284: Make "Start Date" on customer sales tab configurable

guiclient/purchaseOrderItem.cpp
This may conflict with PR #1498
=> Issue #29238: SQL in characteristic query when editing PO Items

guiclient/items.cpp
=> Add Description2 to Items Listing screen

guiclient/displays/dspSalesOrders.cpp, guiclient/openSalesOrders.cpp
=> Issue #28578 Add SO # Search to SO screens

guiclient/apOpenItem.cpp, guiclient/arOpenItem.cpp
=> Issue #29532: Correct Currency Rate on AR/AP Debit/Credit Memos

guiclient/cashReceipt.cpp, guiclient/cashReceipt.h, guiclient/cashReceipt.ui, guiclient/dspCashReceipts.cpp
This has been a constant request from customers.
=> Issue 2903: Post Cash Receipt option from inside CR screen

guiclient/dspAROpenItems.cpp
=> Issue #28773: Add Customer PO to Open Receivables

guiclient/apOpenItem.cpp, guiclient/arOpenItem.cpp
=> issue #29532 - backport to 4.10.1

guiclient/salesOrderItem.cpp
The fix for 29022 introduced more instability than is appropriate
for a point release - 4.10.1. It's safer to revert the commits
d837343 (29022) and cd55e81 (which "fixed" another regression 29739)
than play bug whack-a-mole.
=> issue #29747 - revert fixes for issue #29022 and issue #29739

guiclient/displays/displays.pri, guiclient/displays/dspReturnAuthorizations.cpp, guiclient/displays/dspReturnAuthorizations.h, guiclient/menuSales.cpp, guiclient/menuSales.h
=> Issue #29602: Return Authorization reporting (Lookup screen)

guiclient/salesOrderItem.cpp
The bug was that `sSave(bool)` was called several times when the
user clicked *Save*, including after the cleanup processing had
started. By setting the internal id to -1 as soon as we start the
cleanup, we can reduce the number of unnecessary database queries.
=> issue #29807 - reduce number of queries executed

scriptapi/qtsetup.cpp
QT_VERSION instead of QTVERSION
=> Fix conditional Qt version check for 5.8

common/storedProcErrorLookup.cpp, guiclient/postProduction.cpp, guiclient/postProduction.h
https://github.com/xtuple/xtuple/pull/3018
https://github.com/xtuple/private-extensions/pull/900
=> issue #22868 - Post Production without locking

guiclient/user.cpp, guiclient/user.h, guiclient/user.ui, guiclient/users.cpp
Feature is a big improvement for high user sites and likely can replace some other outstanding issues
=> Issue #29882: Add menu selection to User screen

.gitignore, guiclient/vendor.cpp
this bug was masked by another, where an error check was performed
for the wrong query. also fixed a minor bug where reused
vendor numbers wouldn't be reported properly and removed
unnecessary includes.
=> issue #30120 - resolve fkey bug if no default potype

guiclient/group.cpp, guiclient/group.ui, guiclient/user.cpp
=> Issue #29882: Default user menus from assigned roles

guiclient/customers.cpp
=> Issue #30175: Add customer Type filter to Customers List

guiclient/item.ui
=> Issue #30005: Item master List Price widget size

guiclient/issueToShipping.cpp
Reservations only work for SO so prevent menu option when order type is TO
=> Issue #30134: Prevent reservations menu when order is a TO

guiclient/salesOrder.cpp
Cancel instead of Close line items on deleted prepaid sales order.
=> Issue #28089 Cancel lines instead of closing

guiclient/check.cpp
Show CheckItem amount (pre-discount)
=> Issue #25491 Show CheckItem amount (pre-discount)

common/metrics.h, common/metricsenc.h
=> issue #30138 - fix inheritance so encrypted metrics save correctly

guiclient/reports.cpp
tested on Mac with
xtdesktop      | free floating | workspace
-------------- | ----------------------- | ---------
no             | works | works
native styling | works | works
stylesheet     | works | works
=> issue #30230 - change to positive check when placing the report editor

guiclient/salesOrderItem.cpp
Resolves errors in SO Item.  New feature to allow editing supply orders until the point they are released.
It does this by imploding/re-exploding supply orders to ensure consistency between SO and WO.  Also covers scenario where auto-explode WO setting is true.
=> Issue #30428: Configured Items error on Sales Order item

guiclient/returnAuthorization.cpp
requires xtuple/private-extensions#921
=> issue #29644 - allow extensions to override the raitem list query

guiclient/createLotSerial.cpp, guiclient/createLotSerial.ui
also updated some error checking and simplified handling of whitespace
=> issue #30483 - remove bad error check, treat numbers as numbers

guiclient/salesOrderItem.cpp
Appears to resolve issue raised, but needs additional testing to ensure no side-effects.
=> Issue #30517: SO Item Supply Order qty incorrect with alternate vendor uom

widgets/custcluster.h
Recently revised sql changed column sequence
=> Issue #30575: Customer cluster issues.  

guiclient/project.cpp
Prevent print option when no order types selected.
=> Issue #26348: SQL error on Project Print Orders selection

guiclient/itemAlias.cpp
=> Issue #29435: Item Alias description

guiclient/item.cpp
Hardcoded error messages in item.cpp were missing some error types.  Converted entire messaging to correct itemsite error reporting.
=> Issue #30422: Missing itemsite deletion error message

guiclient/purchaseOrder.cpp
Moved check earlier in process to prevent triplicate error checking and opening PO item in error.
=> Issue #27708: Error msgs when releasing PR with no item cost

guiclient/createRecurringItems.cpp
This resolves the issue at hand, but I am now getting a database SQL error which I think is related to an erroneous foreign key constraint. Still investigating that issue.
Also resolves #27781
=> Issue #30465: Create button on Recurring Items Screen

guiclient/contact.cpp, guiclient/financialLayout.cpp, guiclient/glSeries.cpp, guiclient/glTransaction.cpp, guiclient/incident.cpp, guiclient/invoice.cpp, guiclient/miscCheck.cpp, guiclient/opportunity.cpp, guiclient/postStandardJournal.cpp, guiclient/postStandardJournalGroup.cpp, guiclient/reconcileBankaccount.cpp, guiclient/standardJournal.cpp, guiclient/standardJournalGroup.cpp, guiclient/standardJournalItem.cpp
Refactor to support Gui Error Check.
=> guierrorcheck refactor - round 1

guiclient/salesOrder.cpp, guiclient/salesOrder.h
Updates SO default Site.  Takes preference over Customer Preferred Site unless not supplied.
=> Issue #30094: Ship To Preferred Site now influences Sales Order 

guiclient/displays/dspSalesHistory.cpp, guiclient/displays/dspSummarizedSales.cpp
Also resolves issue where opened list was not auto-populating after opening.
=> issue #30603: Sales History parameters

guiclient/invoiceItem.cpp, guiclient/salesOrderItem.cpp, widgets/itemAliasList.cpp, widgets/itemAliasList.h, widgets/itemCluster.cpp, widgets/itemcluster.h
Fixes several Item alias issues especially around customer specific aliases.
#26127, #24425, #30391
Tested on Quotes, Sales Orders, Invoices.  Can be applied elsewhere using new setCRMAcctId method on the itemCluster.
=> issue #26158, issue #26127, issue #24425, issue #30391: Various Item Alias problems and tidyup

guiclient/configureCRM.cpp, guiclient/crmaccount.cpp
Prevent start number < 1 and handle if it does = 1
=> Issue #17680: Better handling of automatic crm account number generation

guiclient/displays/dspQOHByZone.cpp
=> Issue #30636: Location description in QOH by Zone report

guiclient/postMiscProduction.cpp
=> Issue #16275: Correct Site when posting misc production from inv. availability

guiclient/itemPricingScheduleItem.ui, guiclient/itemPricingSchedules.cpp
Fix double opening of subscreen and widget alignment
=> Issue #30676 & issue #30675 Pricing Schedules

guiclient/financialLayout.cpp, guiclient/financialLayout.h, guiclient/financialLayoutColumns.cpp, guiclient/financialLayoutColumns.ui, guiclient/financialLayoutGroup.cpp
=> Issue #29164: Financial Report validation

common/errorReporter.cpp, guiclient/termses.cpp
Provide user message instead of foreign key SQL error
=> Issue #29291: Additional checks and notifications when deleting terms

guiclient/issueWoMaterialItem.cpp, guiclient/releaseWorkOrdersByPlannerCode.cpp, guiclient/returnWoMaterialBatch.cpp, guiclient/returnWoMaterialItem.cpp
Refactored issueWoMaterialItem.cpp, releaseWorkOrdersByPlannerCode.cpp, returnWoMaterialBatch.cpp, returnWoMaterialItem.cpp
I also thing Brackets modified spacing in areas that don't deal with Gui Error Check Refactors. I don't think this broke anything but let me know if I need to fix it.
=> guierrorcheck refactor - round 5

guiclient/scrapTrans.cpp
Quality workflow script steps.
=> Issue #30810: Additional set() params in scrap transaction to support

guiclient/purchaseOrderItem.cpp
Now checked after selecting the item
=> Issue #29363: Purchase Item supply-ability not checked until save

widgets/itemCluster.cpp, widgets/lotserialCluster.cpp, widgets/lotserialcluster.h, widgets/ordercluster.cpp, widgets/quotecluster.cpp, widgets/revisionCluster.cpp, widgets/virtualCluster.cpp, widgets/widgets.pro
also bring code closer to conforming with coding standards
=> issue #30781 - fix completer bugs

widgets/parameterwidget.cpp, widgets/parameterwidget.h
by making the calculation of preference name more consistent.
Also simplified some of the debugging code.
=> bug #29385 - fix for workspace & free floating modes

widgets/virtualCluster.cpp, widgets/virtualCluster.h
also consolidate completer width code and prepare for reducing
the number of queries called
=> issue #30898, issue #30781 - fix arrow key handling of completers

guiclient/dspAROpenItems.cpp
requires xtuple/xtuple#3160
alternative to xtuple/qt-client#1766
=> issue #29873 - prompt for invoice voiding date

widgets/docAttach.cpp, widgets/docAttach.ui
=> Issue #19555: Allow Quotes (and Return Auths) to be attached as documents

guiclient/invoice.cpp, guiclient/invoice.ui, guiclient/invoiceItem.cpp, guiclient/invoiceItem.ui, guiclient/miscVoucher.cpp, guiclient/miscVoucher.ui, guiclient/voucher.cpp, guiclient/voucher.ui, widgets/comments.cpp, widgets/comments.h
related to but does not require xtuple/xtuple#3166
=> Issue #30948: Add comments to Vouchers, Invoices, and Invoice Items

guiclient/displays/dspTrialBalances.cpp
=> Issue #29623: Add Fiscal Year to Trial Balances report

guiclient/vendor.cpp
Resolves issue, but a bit confusing if you try and create a new vendor from this screen (currently not possible)
=> Issue #30857: Resolve Vendor Workbench selection with auto CRM numbering

guiclient/vendor.cpp, guiclient/vendor.h, guiclient/vendor.ui, guiclient/voucherMiscDistrib.cpp
=> Issue #31105: Vendor default tax type on misc distributions

common/storedProcErrorLookup.cpp, guiclient/createLotSerial.cpp, guiclient/displays/dspWoSchedule.cpp, guiclient/displays/dspWoSchedule.h, guiclient/enterPoReceipt.cpp, guiclient/issueLineToShipping.cpp, guiclient/issueToShipping.cpp, guiclient/issueWoMaterialBatch.cpp, guiclient/issueWoMaterialItem.cpp, guiclient/returnWoMaterialBatch.cpp, guiclient/returnWoMaterialItem.cpp
https://github.com/xtuple/xtuple/pull/3171
https://github.com/xtuple/private-extensions/pull/972
=> issue #30729 - Receiving RA serial controlled item, serial from original SO missing from dropdown

guiclient/addresses.cpp, guiclient/addresses.h, guiclient/contacts.cpp, guiclient/contacts.h, guiclient/prospect.cpp
https://github.com/xtuple/xtuple/pull/3198
=> issue #31217 - add create, edit, view prospect actions to addresses and contacts lists

guiclient/vendor.cpp
This was a regression caused by the fix for 31730.
=> issue #31774, issue #31730 - fix vendor crash

guiclient/project.cpp, guiclient/project.ui
=> issue #31733 - don't show completed tasks by default

guiclient/configureSO.cpp, guiclient/configureSO.ui
Works with https://github.com/xtuple/xtuple/pull/3226
=> issue #32297 - add metric to control default freeform bill-to setting

widgets/xtreewidget.cpp, widgets/xtreewidget.h
These changes contains the merge sort algorithm and sortitems() have that call on the list of topLevelItems.
=> Code changes regarding sort algorithm

widgets/xtreewidget.cpp
make using the GGK performance changes configurable at build time
so we can test them.
=> issue #32340 - revert to old sort method

common/storedProcErrorLookup.cpp, guiclient/displays/dspPartiallyShippedOrders.cpp, guiclient/displays/dspSummarizedBacklogByWarehouse.cpp, guiclient/issueToShipping.cpp, guiclient/openSalesOrders.cpp, guiclient/packingListBatch.cpp, guiclient/salesOrder.cpp, guiclient/salesOrderInformation.cpp, guiclient/shipOrder.cpp, guiclient/shippingInformation.cpp
Associated with xtuple/xtuple#3232, xtuple/private-extensions#994, and xtuple/xdruple-extension#54.
=> Add Tax Hold Type

guiclient/scripttoolbox.cpp, guiclient/userPreferences.cpp, guiclient/userPreferences.ui, scriptapi/qeventloopproto.cpp, scriptapi/qeventloopproto.h, scriptapi/qeventproto.cpp, scriptapi/qeventproto.h, scriptapi/qiodeviceproto.cpp, scriptapi/qnetworkaccessmanagerproto.cpp, scriptapi/qnetworkaccessmanagerproto.h, scriptapi/qnetworkrequestproto.cpp, scriptapi/qnetworkrequestproto.h, scriptapi/scriptapi.pro, scriptapi/scriptapi_internal.h, scriptapi/setupscriptapi.cpp, scriptapi/setupscriptapi.h, widgets/scriptablewidget.cpp, widgets/widgets.cpp
this is a simpler version of #1842 more suitable for a point release
=> issue #31676 - smaller changes for 4_11_x point release

common/common.pro, common/mqlhash.cpp, common/mqlhash.h, common/xcachedhash.cpp, common/xcachedhash.h, guiclient/display.cpp, guiclient/guiclient.cpp, guiclient/guiclient.h, guiclient/scripts.cpp, guiclient/scripttoolbox.cpp, guiclient/xtupleguiclientinterface.cpp, guiclient/xtupleguiclientinterface.h, widgets/guiclientinterface.h, widgets/scriptablewidget.cpp
- this reduces database load from requerying for known mql statements
- this introduces an abstract templated qhash class to build more caches
=> issue #25224 - client-side metasql statement cache

guiclient/main.cpp, guiclient/registrationKeyDialog.cpp, guiclient/registrationKeyDialog.h, guiclient/registrationKeyDialog.ui
- consolidate code
- improve user feedback
- add option to request a new key
=> issue #32534 - set the key regardless of previous state

guiclient/address.cpp, guiclient/contact.cpp, guiclient/enterPoReturn.cpp, guiclient/shipTo.cpp, guiclient/taxAuthority.cpp, guiclient/vendor.cpp, guiclient/vendorAddress.cpp, guiclient/warehouse.cpp, widgets/addressCluster.cpp, widgets/addresscluster.h
This is a more complete implementation of #1893
=> issue #30694 - clarify the consequences of 'changeall' addresses

scriptapitest/scriptapitestresults.cpp
Removed some superfluous headers that were causing problems with MSVC compilation.
=> Removes unnecessary headers to allow MSVC compilation.

guiclient/displays/dspShipmentsBase.cpp
Shipment Reports did not account for single warehouse scenarios in Postbooks systems.
=> [32842] Correct multi-warehouse sql error

common/storedProcErrorLookup.cpp
=> [#32343] Prevent inventory transaction from impacting on Sales Reservations

guiclient/printSinglecopyDocument.cpp, guiclient/printStatementByCustomer.cpp, guiclient/printStatementsByCustomerGroup.cpp, guiclient/printStatementsByCustomerGroup.h, guiclient/printStatementsByCustomerType.cpp
This issue resulted in an erroneous false result from Customer statement selection (not an error).
In testing also found related but different refresh bug in the Statement by Customer Group code.
=> [25322] Fix erroneous results from Customer Statements

guiclient/purchaseOrder.cpp
Plus refresh the Open PO list to clear temporary entry
=> [31859] Resolve SQL error when cancelling POs

guiclient/printMulticopyDocument.cpp, guiclient/unpostedPurchaseOrders.cpp
Resolved Open PO screen overriding user preference for unposted PO checkbox.
Tidied up logic around Post Invoice checkbox when printing invoices.
=> [31164] Open PO and Post Invoice checkbox settings

guiclient/salesOrder.ui
=> Revert "[32680] Make Ship Via on Sales Orders editable"

common/storedProcErrorLookup.cpp, guiclient/postCheck.cpp, guiclient/postChecks.cpp, guiclient/viewCheckRun.cpp
Notify user when no valid payments to post.
Additional checks on payment status before posting.  Resolved latent sql bug when posting payments.
=> [32113] Fix ability to post unprinted payments. 

guiclient/invoice.cpp, guiclient/invoice.h
- Reset invoice number on cancel
- Remove duplicate code
- Modernise MessageBoxes
- Refresh invoice list on deleting invoices
=> [30473] Various invoice fixes.  

guiclient/project.cpp
Translatable labels requires xtuple/xtuple#3277
=> Improvements to Project Task List Report

guiclient/salesOrder.cpp
Prevent scenario where user can delete SO items and leave the SO in a closed, orphaned state
=> [30500] Prevent orphaned SO headers, plus refresh order list on delete

guiclient/voucherMiscDistrib.cpp
=> [33218] Correctly populate misc. voucher distributions when editing 

common/storedProcErrorLookup.cpp, guiclient/enterPoitemReceipt.cpp, guiclient/item.cpp
Also prevents amending an item type if the item site validation checks would fail
requires xtuple/xtuple#3313
=> [33238] Prevent ability to receipt into inactive item sites.

guiclient/avalaraIntegration.cpp, guiclient/avalaraIntegration.h, guiclient/configureTax.cpp
Includes test functionality in the Tax Integration setup.
=> Initial commit of Avalara REST communication class.  

guiclient/prospect.cpp, guiclient/prospect.h, guiclient/prospect.ui, guiclient/taskList.cpp, widgets/parameterwidget.cpp, widgets/parameterwidget.h
=> CRM v5_0:  Add Tasks to Prospects

widgets/contactWidget.cpp
But force save email as lower case.
Also fixed some extraneous code
=> [33448] Modify contact email validator to allow entry of capitals

guiclient/guiclient.cpp
thanks to @ChristopherCotnoir for finding the cause
=> [33554] restore script exposure of the setup window api

common/storedProcErrorLookup.cpp, guiclient/salesOrder.cpp, guiclient/salesOrderItem.cpp
Reinstate logic to create WOs. Also added hard check to prevent duplicate WOs from being created from SO lines (there was another issue raised about this).  This hard check needs to be confirmed.
requires xtuple/xtuple#3362
=> [33100] Create WO checkbox in Sales Order Line was not working.  

guiclient/configureEncryption.cpp, guiclient/configureEncryption.h, guiclient/configureEncryption.ui
create initial key with a hash.
Also adds information about distribution of the key and the consequences of altering the key.
=> [11525] Encryption key generation feature.  Creates and populates initial key

guiclient/opportunityList.cpp
Uses case insensitive pattern match
requires xtuple/xtuple#3388
=> [14260] Add Opportunity Name filter to Opp List.  

guiclient/reconcileBankaccount.cpp
So you only see one bank account option for each separate bank GL Asset account.
=> [33639] Consolidate Bank Reconciliation accounts based on GL account

guiclient/project.cpp
=> [29001] Add assignees to Project activity list

guiclient/customer.cpp
Plus resolve some bugs in the customer workbench found in testing
=> [26600] Display Customer projects directly in the Customer Workbench

guiclient/menuProducts.cpp
requires xtuple/private-extensions#1028
=> [10146] Add missing menu privileges

guiclient/salesOrder.ui
no idea why it ended up being such a big diff.  Was carefully edited...
=> Rejig Sales Order line items screen to better align widgets (Avalara Tax)

scriptapi/qscrollarea.cpp, scriptapi/qscrollarea.h, scriptapi/scriptapi.pro, scriptapi/setupscriptapi.cpp
So I get access to ensureWidgetVisible()
=> Expose QScrollArea to script using QMetaObject

guiclient/displays/dspUninvoicedReceivings.cpp
=> [11094] Add purchase cost to uninvoiced receivings screen and report

common/login2.cpp, common/login2.h, guiclient/guiclient.cpp, guiclient/guiclient.h, guiclient/main.cpp, guiclient/user.cpp
make the login code more direct and remove cruft to
ensure the client reports db connection info correctly
and reduce the risk of logging in to the wrong db.
=> [32371] reduce chance of logging in to wrong db

guiclient/dspFinancialReport.cpp, guiclient/dspFinancialReport.h, guiclient/main.cpp, guiclient/uiform.ui, guiclient/userPreferences.ui, widgets/characteristicAssignment.cpp
Also updated some  copyright dates
=> [16877] Enable printing Financial Report from preview window

guiclient/salesOrderItem.cpp
SO Item expected customer id to be passed into the set() function.  This did not happen from project (and potentially other sources)
=> [33730] Fix incorrect pricing when accessing sales order items directly

guiclient/packingListBatch.cpp, guiclient/packingListBatch.ui, guiclient/printPackingList.cpp
=> [33754] Tidy up some Packing List Batch issues - especially around TOs

common/login2.cpp
froglogic's Squish does not allow the PostgreSQL config parameter
application_name to be passed when connecting, so make it optional
when logging in. Also simplify some problem reporting and Recent
menu handling.
=> allow logging in with standard squish build

guiclient/configureCRM.cpp, guiclient/configureCRM.ui, guiclient/displays/displays.pri, guiclient/displays/dspDocuments.cpp, guiclient/displays/dspDocuments.h, guiclient/menuCRM.cpp, guiclient/menuCRM.h, widgets/docAttach.cpp, widgets/docAttach.h, widgets/docAttach.ui, widgets/docCluster.cpp, widgets/doccluster.h, widgets/documents.cpp, widgets/plugins/docclusterplugin.h, widgets/widgets.cpp, widgets/widgets.pro
Allow document to be assigned to multiple sources. 
Document display for searching/listing documents in the system.
Assign characteristics to documents.  
Document assignment notes.
Rudimentary document privilege system.
=> [25092] Document Enhancements

guiclient/createLotSerial.cpp, guiclient/distributeInventory.cpp, guiclient/enterPoReceipt.cpp, guiclient/issueToShipping.ui, guiclient/postProduction.cpp, guiclient/postProduction.ui, guiclient/transferOrders.ui, widgets/warehousegroup.cpp, widgets/warehousegroup.h
Plus lock down some options and other quality of life improvements
=> [33279] Resolve further lot/serial bugs on W/O post production. 

guiclient/customer.cpp, widgets/custCluster.cpp, widgets/custcluster.h
Had to add an understanding of mode to the CustCluster widget
=> [33895] Fix privilege preventing creation of a new customer

guiclient/contacts.cpp, guiclient/prospect.cpp, widgets/contactWidget.cpp, widgets/contactwidget.h
=> [28321] Add Company field to CRM Contact record

guiclient/purchaseOrder.cpp, widgets/ordercluster.cpp
Plus resolve incorrect orderCluster extraClause
=> [33858] Fix PO OrderCLuster missing order type

scriptapi/qtablewidgetitemproto.cpp, scriptapi/qtablewidgetitemproto.h, scriptapi/qtablewidgetproto.cpp, scriptapi/qtablewidgetproto.h, scriptapi/scriptapi.pro, scriptapi/setupscriptapi.cpp
Exposes the qtablewidget and qtableitemwidget classes to scripting.
=> Expose qtablewidget

common/login2.cpp
'goto' is required to break out of nested loops. otherwise
we break out of the inner loop on success and try the outer
loop a few more times, eventually failing to connect.
=> fix problem with changes for squish

common/storedProcErrorLookup.cpp
I am not sure where those deletions came from but here are the added translations by themselves
=> [18464] Reflect changes to armemo.paid in aropen table 

guiclient/createRecurringItems.cpp, guiclient/createRecurringItems.ui, guiclient/salesOrder.cpp, guiclient/salesOrder.ui
Client code and ui forms to enable creating recurring sales orders.
=> Recurring salesorder

guiclient/crmGroups.ui
This issue actually affected _all_ CRM Groups screens, simple fix.
=> [34073] Resolve View button on CRM Groups

guiclient/project.cpp, guiclient/project.ui
=> [34072] Create Project from Opp - project status error

guiclient/project.cpp
Also resolves issue [34075]
requires xtuple/xtte#72
=> [34075] [34076] Resolve Project Activities edit/view access and list refresh

guiclient/vendorType.cpp, guiclient/vendorType.ui, guiclient/vendorTypes.cpp
Properly align widgets on screen.  
Add default visibility to Vendor Types list.
=> [34079] Fix missing Vendor Type Default Label.

guiclient/characteristic.cpp, guiclient/characteristic.ui
as it was defaulting to first item in combobox
=> Set new characteristic input mask to empty/null

guiclient/opportunity.cpp, guiclient/project.cpp, guiclient/prospects.cpp, widgets/docAttach.cpp, widgets/docAttach.h
Some document related bugfixes found in version 5.0 regression testing.
This commit may need to be backported to 4.12 [**UPDATE** - tested in 4.12 and same issues are not present in that version]
requires xtuple/xtuple#3506
=> Document Assignment bugfixes and Project/document fixes

guiclient/display.cpp, guiclient/display.ui, guiclient/displayprivate.h
Added record count to XDisplay statusBar.  Uses query size so should not impact performance much (at all??)
=> [33309] Add Record count to all lists (XDisplay lists)

guiclient/prospect.cpp
=> [34293] Resolve new Prospect bug when Contact is associated 

widgets/xcombobox.cpp
=> [33126] Resolve refresh on Currency combobox when currencies added

widgets/xtreewidget.cpp
=> [34443] Revert "Add missing connections"

common/avalaraIntegration.h, common/noIntegration.cpp, common/taxIntegration.cpp, common/taxIntegration.h, guiclient/guiclient.cpp, scriptapi/setupscriptapi.cpp
and fix some compiler warnings
=> add script exposure to tax integration

guiclient/voucherItem.cpp
see https://github.com/xtuple/qt-client/pull/2219
=> [34506] backport from 5_0_x

common/applock.cpp, widgets/ordercluster.cpp
requires https://github.com/xtuple/xtuple/pull/3566
=> [34341] fix locking problem usually seen on web-enabled dbs

guiclient/purchaseOrderItem.cpp, guiclient/purchaseOrderItem.h, guiclient/salesOrderItem.cpp, guiclient/salesOrderItem.h
Adds signals to sSave in purchase order item and sales order item.
Enum for setting failed status is not yet working in scripts.
=> Ssave signals

guiclient/exportData.cpp
=> [34458] adjust desktop client for openrpt api change

guiclient/guiclient.pro, scriptapi/scriptapi.pro, scriptapi/setupscriptapi.cpp, widgets/widgets.pro
=> Allow building with Qt 5.5.1

guiclient/salesOrderItem.cpp
Logic failed for quotes.  Needs to upmerge to 5.0 as well.
=> Correct logic flaw in customer determination found when reviewing code

common/storedProcErrorLookup.cpp
=> [18611] Fix minor formatting problem on recursive BOM error msg

guiclient/salesOrderItem.cpp
=> [34668] Fix bug with Sales Order Item configurable items

guiclient/employee.cpp
Tested version 5.0 and same error does not exist
=> [33801] Employee contact save error

guiclient/location.cpp
Allows reporting of occasional serial problem.
=> [33867] Add missing error reporting to location screen

guiclient/task.cpp
=> [34302] Release Task number when cancelling the screen

guiclient/project.cpp, guiclient/projectType.cpp, guiclient/projectType.ui, guiclient/projectTypes.cpp
=> [34687] Add Project Type default setting to assist in Project entry

guiclient/project.ui
Resolves issues #34739 & #34740
=> [34740] Resolve Project ui alignment issues

guiclient/project.ui
=> [34739] Add Contact Label to Project screen (4.12)

common/storedProcErrorLookup.cpp, guiclient/configureCRM.cpp, guiclient/configureCRM.h, guiclient/configureCRM.ui
And prepare for external validation service integration.
requires xtuple/xtuple#3604
=> [23942] Add basic email validation

guiclient/prospect.cpp
loosely related to xtuple/xtuple#3607
=> [34786] Resolve characteristic issues with new Prospects

guiclient/contactAccountAssign.cpp
... did not update the underlying contact list.
=> [34787] Updating the Contact/Account role assignment

guiclient/contact.cpp, guiclient/contact.ui
in the Contact relationship list.
requires xtuple/xtuple#3608
=> [34782] Add checkbox to show/hide inactive CRM Roles

widgets/plugins/selectionwidgetplugin.h, widgets/selectionwidget.cpp, widgets/selectionwidget.h, widgets/selectionwidget.ui, widgets/widgets.cpp, widgets/widgets.pro
Initial commit of the selection widget. Gil has already suggested a rewrite of the sql generating portion in metasql for the next iteration.
=> Selection Widget initial commit

guiclient/item.cpp
as tooling items allow inventory
requires xtuple/xtuple#3614
=> [34671] Allow item type changes to tooling when inventory exists

xtuple.pro
There is a corresponding change and pull request for openrpt
=> generate translations for msvc

guiclient/issueLineToShipping.cpp, guiclient/issueToShipping.cpp
Resolve COGS bug where a job costed item was not generating COGS entries due to not finding an appropriate item cost from the W/O.
requires xtuple/xtuple#3611
=> [34761] Revert closing of job costed W/O to shipping transaction.  

widgets/selectionwidget.cpp, widgets/selectionwidget.h, widgets/selectionwidget.ui
Addresses remaining comments from code review.
=> Selection widget

guiclient/displays/dspProjectSummary.cpp
=> [35031] query doesn't run because setParams wasn't true

guiclient/buildCRMGroups.cpp
=> [35093] Additional Customer parameters for Build CRM Groups utility

guiclient/project.ui
=> [35035] Make window more compact

guiclient/project.cpp, guiclient/projects.cpp
Also fixed project status label on Projects List
requires xtuple/xtuple#3651
=> [35073] Resolve project status inconsistencies in the project task list

guiclient/customer.cpp
(cherry picked from commit 39b5eb18b60ba4390d985ea3f70cb26e0259d43c)
=> [35040] [Backport] Set Allow Free Form Bill-To default

widgets/parameterwidget.cpp
(cherry picked from commit b68a8a57ba92287cdb25850fdcaaaa14891911aa)
=> [34045] [Backport] make the parameter widget less sensitive to bad data

guiclient/lotSerialRegistration.cpp, guiclient/lotSerialRegistration.h, guiclient/lotSerialRegistration.ui
(cherry picked from commit ba2ec301ac3b49fe4cf0664baa02bf56e419d1c9)
(cherry picked from commit 34024e082fff655d94ea5989438dbaecfe131095)
=> [35024] [Backport] Cleanup properly on reject()

guiclient/poitemTableView.cpp
(cherry picked from commit 43c99733765798d440e626fa856531d0280a6494)
=> [35039] [Backport] Updated query

widgets/woCluster.cpp
(cherry picked from commit af35b9746dc38bc08e646a86a8e4aea31390f6dd)
=> [35048] [Backport] Sort womatlCluster

guiclient/configureIM.cpp
(modified from commit e945e72f8012e979c665868999f4f98448e3b9de)
=> [34106] [Backport] Resolve issues with Inventory configuration

guiclient/salesOrderItem.cpp, guiclient/salesOrderItem.h
(cherry picked from commit 5800d859a3032030006c6f26f382f21612bb3180)
(cherry picked from commit a2a4d5f53aa9e5fe8576dd5899e3f9b049beb6ea)
=> [34954] [Backport] Use correct item id

guiclient/unpostedPoReceipts.cpp
(cherry picked from commit fcb12af269041f2e56464204074bae1f4779788e)
=> [33598] [Backport] Fix date comparison

guiclient/addresses.cpp, guiclient/contacts.cpp, guiclient/incidentWorkbench.cpp, guiclient/opportunityList.cpp, guiclient/projects.cpp, guiclient/todoList.cpp
(cherry picked from commit 3b999345b0cc81a78a8aadca5c63fd72ee722cb0)
=> [35112] [Backport] Make dialogs modal if parent is modal

guiclient/displays/dspShipmentsBase.cpp
(cherry picked from commit 4cd0fc4d1fd91d65c89fd9db5d8074d935661818)
=> [35108] [Backport] Don't query for Transfer Orders in SO mode

guiclient/returnAuthorizationWorkbench.cpp
(cherry picked from commit b937b949933f89de1dc434cd44effa3578f7b7f5)
=> [35146] [Backport] Added double-click functionality

guiclient/contact.ui
(cherry picked from commit 2849a56d198c7acd6815ae651adb8669fe42623d)
=> [35070] [Backport] Fix size issues
